### ISSUE TITLE
what is latest version released?

### ISSUE THREAD

**Issue by RockScience** [man-group/ArcticDB#1018]
### Describe the bug

is version 1.6.2 after v4.0.0 ?

![image](https://github.com/man-group/ArcticDB/assets/5772226/d486894f-708b-4724-842b-2e62b4fab462)

### Steps/Code to Reproduce

not relevant

### Expected Results

v4.0.x ?

### OS, Python Version and ArcticDB Version

not relevant

**Comment by vasil-pashov** [comment]
We are following semantic versioning: https://semver.org/. Thus 4.0.0 is the latest and greatest, 1.6.2 is backporting features for an old release.
