### ISSUE TITLE
Error when appending data to large LMDB database

### ISSUE THREAD

**Issue by river7816** [man-group/ArcticDB#1031]
### Describe the bug

```python
Traceback (most recent call last):
  File "/home/yefei/river/read_from_arcticdb.py", line 90, in <module>
    lib.append('Factors', df_final, prune_previous_versions=True)
  File "/home/yefei/miniforge-pypy3/envs/rqsdk/lib/python3.10/site-packages/arcticdb/version_store/library.py", line 698, in append
    return self._nvs.append(
  File "/home/yefei/miniforge-pypy3/envs/rqsdk/lib/python3.10/site-packages/arcticdb/version_store/_store.py", line 692, in append
    vit = self.version_store.append(
arcticdb_ext.exceptions.InternalException: std::runtime_error(Invalid lmdb error code -30792 while putting key d:Factors:814:0x5c4e9c027e85b65d@1699086748797728046[1299542400000000000,1299542400000000001])
```
I thought it was the limit size of the lmdb so I try to set the mapsize to 900GB `ac = Arctic('lmdb:///home/yefei/Database?map_size=900GB')`. I thought there is no limit on linux until I reach the physical limit of my disk. 

Here is my usage:
```
(rqsdk) yefei@yefei:~/river$ df -h
文件系统        大小  已用  可用 已用% 挂载点
tmpfs            32G   31M   32G    1% /run
/dev/nvme0n1p2  938G  572G  319G   65% /
tmpfs           158G  4.0K  158G    1% /dev/shm
tmpfs           5.0M     0  5.0M    0% /run/lock
/dev/nvme0n1p1  511M  6.1M  505M    2% /boot/efi
tmpfs            32G  1.7M   32G    1% /run/user/1000
```

### Steps/Code to Reproduce

```python
import pandas as pd
from read_from_arcticdb import save_list_to_pickle, load_list_from_pickle
from rqdatac import *
import rqdatac as rq
from tqdm import tqdm
from arcticdb import Arctic
import gc
rq.init('18964677307','123456')
ac = Arctic('lmdb:///home/yefei/Database?map_size=900GB')
lib = ac['FinancialData']
dates = load_list_from_pickle('dates.pkl')
stock = load_list_from_pickle('stocks.pkl')
# dates_download= []
dates_download = load_list_from_pickle('dates_download.pkl')

batch_size = 100
dates_batch = [dates[i:i + batch_size] for i in range(0, len(dates), batch_size)]
dates_batch = [x for x in dates_batch if x not in dates_download]
df1 = lib.read('dividend', date_range=(pd.Timestamp('2005-01-04'),pd.Timestamp('2005-6-04'))).data
print('Downloading Ricequant data...')
for batch in tqdm(dates_batch):
    # df =  get_price(stock, start_date=batch[0], end_date=batch[-1], frequency='1m', adjust_type='pre', fields=['open','low','high','close','volume','num_trades','total_turnover']).reset_index('order_book_id').sort_index()
    df = get_dividend(order_book_ids=stock, start_date=batch[0], end_date=batch[-1]).reset_index('order_book_id').sort_index()
    df[['round_lot']] = df[['round_lot']].astype(float)
    df = df.reindex(columns=df1.columns)
    if batch[0] == dates[0]:  # Check if it's the first batch
        lib.write('dividend', df, prune_previous_versions=False)
    else:
        lib.append('dividend', df, prune_previous_versions=True)
    del df
    gc.collect()
    dates_download.append(batch)
    save_list_to_pickle(dates_download, 'dates_download.pkl')
```

### Expected Results

NO error is thrown

### OS, Python Version and ArcticDB Version

Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
OS: Linux-6.2.0-34-generic-x86_64-with-glibc2.35
ArcticDB: 4.0.0

### Backend storage used

LMDB

### Additional Context

No

**Comment by joe-iddon** [comment]
Hi @river7816. This does seem like a map size error as you say. It is strange that setting a larger size did not help. Could you try incrementally increasing the size please from a small value and see if as you increase it your appends progress further? This should help us debug at what size it does not allow you to write mote data.

You'll have to delete the library when you initially reduce the size to something small, otherwise it will remain at the larger size. [See the LMDB documentation here.](http://www.lmdb.tech/doc/group__mdb.html#gaa2506ec8dab3d969b0e609cd82e619e5).

**Comment by muhammadhamzasajjad** [comment]
Hi @river7816. I tried to reproduce the error following the code snippet you provided, but I haven't been able to reproduce it. I could not use the exact code you provided as it reads from your `pickle` files and uses custom modules and functions. 

For reproducing the isue, I created an LMDB Database with a small `map_size` not enough to append a dataframe of 100,000 rows. Then I increased `map_size` in another python session to `900GB` and I have been able to write the data successfully.

If you were doing this in a Jupyter Notebook, note that you should only have one `Arctic` object instance in one session.
I would also highly recommend using the latest ArcticDB version (currently 4.2.1) and re-test the issue, as there were several bugs relating to LMDB in the older versions like 4.0.0.
