### ISSUE TITLE
Using QueryBuilder on grouping column with floats fails on Linux Conda

### ISSUE THREAD

**Issue by G-D-Petrov** [man-group/ArcticDB#1035]
### Describe the bug

Using QueryBuilder on grouping column with floats fails on Linux Conda.
The bigger problem is that this doesn't reproduce on all versions.
It has been experienced only on Linux Conda on self-hosted ec2 runners and only on release builds.

Can be reproduced with the following test - test_group_on_float_column_with_nans

### Steps/Code to Reproduce

``` python 
ac = Arctic("lmdb://test_dir")
ac.create_library("some_lib")
lib = ac["some_lib"]
sym = "test_group_on_float_column_with_nans"
df = pd.DataFrame({"grouping_column": [1.0, 2.0, np.nan, 1.0, 2.0, 2.0], "agg_column": [1, 2, 3, 4, 5, 6]})
lib.write(sym, df)
expected = df.groupby("grouping_column").agg({"agg_column": "sum"})
q = QueryBuilder()
q = q.groupby("grouping_column").agg({"agg_column": "sum"})
received = lib.read(sym, query_builder=q).data
received.sort_index(inplace=True)
assert_frame_equal(expected, received)
```

### Expected Results

The columns are correctly grouped like this:

1.0                       5
2.0                      13

### OS, Python Version and ArcticDB Version

Python: 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
OS: Linux-6.2.0-1015-aws-x86_64-with-glibc2.35
ArcticDB: 1.4.1.dev0

### Backend storage used

LMDB

**Comment by jjerphan** [comment]
This error sporadically happens on `master` already for Linux conda-build only.

For instance see: https://github.com/man-group/ArcticDB/actions/runs/6801380964/job/18492095030#step:10:502

**Comment by alexowens90** [comment]
We're on `v0.6.5`, which was released in April 2018. It seems to be quite actively maintained, and `v0.8.2` was released in July 2023, we should try upgrading to the latest version in case they fixed the issue in the interim.
