### ISSUE TITLE
Symbol list doesn't work on Azure and mem storage in read-only mode

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#1061]
### Describe the bug

Even though Azure users currently won't have access to read-only mode, the failing test still indicates a wrong assumption or implementation issue with the storage.

### Steps/Code to Reproduce

`test_turning_on_symbol_list_after_a_symbol_written`

### Expected Results

It passes when `no_*` marks are removed.

### OS, Python Version and ArcticDB Version

Any

### Backend storage used

Azure, mem

**Comment by poodlewars** [comment]
Even this simplified test case fails,

```
def test_turning_on_symbol_list_after_a_symbol_written(in_memory_store_factory):
    # The if(!maybe_last_compaction) case
    lib: NativeVersionStore = in_memory_store_factory(symbol_list=False)

    lib.write("a", 1)
    assert not lib.library_tool().find_keys(KeyType.SYMBOL_LIST)

    lib = in_memory_store_factory(reuse_name=True, symbol_list=True)

    # For some reason, symbol_list=True is not always picked up on the first call, so forcing it:
    symbols = lib.list_symbols(use_symbol_list=True)
    assert set(symbols) == {"a"}
```
