### ISSUE TITLE
Infinite redirection on docs.arcticdb.io/api/

### ISSUE THREAD

**Issue by arthur-c** [man-group/ArcticDB#1067]
### Describe the bug

The web server config is broken for the URL `https://docs.arcticdb.io/api/` (with final `/`) and triggers an infinite URL rewriting :

`https://docs.arcticdb.io/api/latest/latest/latest/latest/latest/latest/latest/latest/latest/latest/`
Tested with 3 different browsers.

### Steps/Code to Reproduce

Got to `https://docs.arcticdb.io/api/`

### Expected Results

https://docs.arcticdb.io/api/latest/

### OS, Python Version and ArcticDB Version

N/A

**Comment by alexowens90** [comment]
Hi @arthur-c, thanks for flagging, I'll let our website team know about the issue

**Comment by jamesmunro** [comment]
@arthur-c a working link is e.g. https://docs.arcticdb.io/4.1.0/api (for version 4.2.0)

**Comment by jamesmunro** [comment]
I've added redirects and 404s.  Should all be solved.
