### ISSUE TITLE
InternalException: lmdb::runtime_error(mdb_txn_begin: Invalid argument)

### ISSUE THREAD

**Issue by maohui** [man-group/ArcticDB#1078]
### Describe the bug

when I run the articDB by Arctic(f'lmdb://{arctic_path}'), sometimes it will show the error like this:
InternalException: lmdb::runtime_error(mdb_txn_begin: Invalid argument), but sometime it runs successfully.

### Steps/Code to Reproduce

from arcticdb import Arctic

class DataManager:
    def __init__(self, arctic_path):
        
        self.ac = Arctic(f'lmdb://{arctic_path}')
        
        if 'xxx' not in self.ac.list_libraries():
            self.ac.create_library('xxx')

dm = DataManager(ArcticPath)

---> 51 self.ac = Arctic(f'lmdb://{arctic_path}')
     52 self.data_source = data_source
     53 if 'universe' not in self.ac.list_libraries():

File /opt/anaconda3/envs/py310/lib/python3.10/site-packages/arcticdb/arctic.py:171, in Arctic.__init__(self, uri, encoding_version)
    169 self._encoding_version = encoding_version
    170 self._library_adapter = _cls(uri, self._encoding_version)
--> 171 self._library_manager = LibraryManager(self._library_adapter.config_library)
    172 self._uri = uri
    173 self._open_libraries = dict()

File /opt/anaconda3/envs/py310/lib/python3.10/site-packages/arcticdb/adapters/lmdb_library_adapter.py:137, in LMDBLibraryAdapter.config_library(self)
    133 env_cfg = EnvironmentConfigsMap()
    135 add_lmdb_library_to_env(env_cfg, lib_name=self.CONFIG_LIBRARY_NAME, env_name=_DEFAULT_ENV, db_dir=self._path)
--> 137 lib = NativeVersionStore.create_store_from_config(
    138     env_cfg, _DEFAULT_ENV, self.CONFIG_LIBRARY_NAME, encoding_version=self._encoding_version
    139 )
    141 return lib._library

File /opt/anaconda3/envs/py310/lib/python3.10/site-packages/arcticdb/version_store/_store.py:261, in NativeVersionStore.create_store_from_config(cls, cfg, env, lib_name, open_mode, encoding_version)
    259 lib_cfg = extract_lib_config(cfg.env_by_id[env], lib_name)
    260 lib_cfg.lib_desc.version.encoding_version = encoding_version
--> 261 lib = cls.create_lib_from_lib_config(lib_cfg, env, open_mode)
    262 return cls(library=lib, lib_cfg=lib_cfg, env=env, open_mode=open_mode)

File /opt/anaconda3/envs/py310/lib/python3.10/site-packages/arcticdb/version_store/_store.py:269, in NativeVersionStore.create_lib_from_lib_config(lib_cfg, env, open_mode)
    267 cfg_resolver = _create_mem_config_resolver(envs_cfg)
    268 lib_idx = _LibraryIndex.create_from_resolver(env, cfg_resolver)
--> 269 return lib_idx.get_library(lib_cfg.lib_desc.name, _OpenMode(open_mode))

InternalException: lmdb::runtime_error(mdb_txn_begin: Invalid argument)

### Expected Results

No error throw

### OS, Python Version and ArcticDB Version

Python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
OS: Linux-5.4.0-162-generic-x86_64-with-glibc2.31

ArcticDB: 4.0.0

### Backend storage used

LMDB

**Comment by G-D-Petrov** [comment]
Hi @maohui,
This seems to be an error with lmdb and not ArcticDB itself.
Can you provide more context on what is your use case?
Are multiple processes trying to use the same client?

**Comment by maohui** [comment]
The use case is like:
I connect my remote jupyter lab in one computer, and connect to the ArcticDB. Then I change one computer and also connect to that jupyter lab, and try to connect to the same ArcticDB. Is this the case I am trying to use the same client in the same process?

**Comment by G-D-Petrov** [comment]
LMDB doesn't support remote file systems (ref [here](https://stackoverflow.com/questions/61365680/lmdb-error-lmdb-lockerror-mdb-txn-begin-resource-temporarily-unavaliable)).
For your setup, I'd suggest connecting to S3, either through AWS or you can look into [minio](https://min.io/)

**Comment by maohui** [comment]
sure. Thanks
