### ISSUE TITLE
Using Google Cloud Storage as a backend

### ISSUE THREAD

**Issue by 8W9aG** [man-group/ArcticDB#1096]
**Is your feature request related to a problem? Please describe.**
I would like to run arcticDB on google cloud, however it seems to just offer S3 and Azure options for storage.

**Describe the solution you'd like**
Explicit support for google cloud.

**Describe alternatives you've considered**
Can the S3 extension connect to Google Cloud using some sort of adapter? Is this a known workflow?

**Additional context**
I would be more than happy to work on this if the ArcticDB team consider it a worthy feature.

**Comment by G-D-Petrov** [comment]
Hi @8W9aG ,
Support for Google Cloud Storage as a backend is in our backlog but is currently **not** a priority for us.
I see that you are interested in working on this - we encourage and welcome such contributions.
Please [refer to our contribution guidelines](https://github.com/man-group/ArcticDB/blob/master/docs/mkdocs/docs/technical/contributing.md) and feel free to open a PR on GitHub - we will be happy to review your changes.

**Comment by maxim-morozov** [comment]
Duplicated
