### ISSUE TITLE
`test_move_s3_library` failing on CI sporadically

### ISSUE THREAD

**Issue by Hind-M** [man-group/ArcticDB#1112]
### Describe the bug

Failing test on [CI](https://github.com/man-group/ArcticDB/actions/runs/7017841721/job/19092022118?pr=1089) with the following log:

=================================== FAILURES ===================================
_____________________________ test_move_s3_library _____________________________

moto_s3_endpoint_and_credentials = ('http://localhost:56363', '56363', 'test_bucket_883', 'awd', 'awd')

    def test_move_s3_library(moto_s3_endpoint_and_credentials):
        # Given - any S3 library
        (
            endpoint,
            port,
            bucket,
            aws_access_key,
            aws_secret_key,
        ) = moto_s3_endpoint_and_credentials
    
        original_uri = (
            endpoint.replace("http://", "s3://").rsplit(":", 1)[0]
            + ":"
            + bucket
            + "?access="
            + aws_access_key
            + "&secret="
            + aws_secret_key
            + "&port="
            + port
        )
    
        ac = Arctic(original_uri)
        ac.create_library("lib")
        lib = ac["lib"]
    
        df = get_wide_dataframe(size=100)
        lib.write("sym", df)
    
        # When - we move the data
        client = boto3.client(
            service_name="s3",
            endpoint_url=endpoint,
            aws_access_key_id=aws_access_key,
            aws_secret_access_key=aws_secret_key,
            region_name=moto.s3.responses.DEFAULT_REGION_NAME,
        )
        new_bucket = f"{bucket}-dest"
        client.create_bucket(Bucket=new_bucket)
    
        s3 = boto3.resource(
            service_name="s3",
            endpoint_url=endpoint,
            aws_access_key_id=aws_access_key,
            aws_secret_access_key=aws_secret_key,
        )
        source = s3.Bucket(bucket)
        dest = s3.Bucket(new_bucket)
    
        for obj in source.objects.filter():
>           dest.copy({"Bucket": bucket, "Key": obj.key}, obj.key)

tests/integration/arcticdb/test_arctic_move_storage.py:174: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/root/micromamba/envs/arcticdb/lib/python3.10/site-packages/boto3/s3/inject.py:508: in bucket_copy
    return self.meta.client.copy(
/root/micromamba/envs/arcticdb/lib/python3.10/site-packages/boto3/s3/inject.py:441: in copy
    with create_transfer_manager(self, new_config) as manager:
/root/micromamba/envs/arcticdb/lib/python3.10/site-packages/boto3/s3/transfer.py:169: in create_transfer_manager
    if _should_use_crt(config):
/root/micromamba/envs/arcticdb/lib/python3.10/site-packages/boto3/s3/transfer.py:200: in _should_use_crt
    logger.debug(
/root/micromamba/envs/arcticdb/lib/python3.10/logging/__init__.py:1465: in debug
    self._log(DEBUG, msg, args, **kwargs)
/root/micromamba/envs/arcticdb/lib/python3.10/logging/__init__.py:1624: in _log
    self.handle(record)
/root/micromamba/envs/arcticdb/lib/python3.10/logging/__init__.py:1634: in handle
    self.callHandlers(record)
/root/micromamba/envs/arcticdb/lib/python3.10/logging/__init__.py:1696: in callHandlers
    hdlr.handle(record)
/root/micromamba/envs/arcticdb/lib/python3.10/logging/__init__.py:968: in handle
    self.emit(record)
/root/micromamba/envs/arcticdb/lib/python3.10/site-packages/_pytest/logging.py:372: in emit
    super().emit(record)
/root/micromamba/envs/arcticdb/lib/python3.10/logging/__init__.py:1108: in emit
    self.handleError(record)
/root/micromamba/envs/arcticdb/lib/python3.10/logging/__init__.py:1100: in emit
    msg = self.format(record)
/root/micromamba/envs/arcticdb/lib/python3.10/logging/__init__.py:943: in format
    return fmt.format(record)
/root/micromamba/envs/arcticdb/lib/python3.10/site-packages/_pytest/logging.py:136: in format
    return super().format(record)
/root/micromamba/envs/arcticdb/lib/python3.10/logging/__init__.py:678: in format
    record.message = record.getMessage()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <LogRecord: boto3.s3.transfer, 10, /root/micromamba/envs/arcticdb/lib/python3.10/site-packages/boto3/s3/transfer.py, 2...ger. Preferred client: {pref_transfer_client}, CRT available: {HAS_CRT}, Instance Optimized: {is_optimized_instance}.">

    def getMessage(self):
        """
        Return the message for this LogRecord.
    
        Return the message for this LogRecord after merging any user-supplied
        arguments with the message.
        """
        msg = str(self.msg)
        if self.args:
>           msg = msg % self.args
E           TypeError: not all arguments converted during string formatting

### Steps/Code to Reproduce

Failing sporadically on the CI

### Expected Results

Success

### OS, Python Version and ArcticDB Version

Python 3.10.13 | ArcticDB 4.1.0

**Comment by poodlewars** [comment]
Qi made some robustness changes to the fixtures. This doesn't seem to still be happening.
