### ISSUE TITLE
The files in the ver folder will not be deleted after running prune_previous_versions

### ISSUE THREAD

**Issue by XiaoHuiHui233** [man-group/ArcticDB#1175]
### Describe the bug

In my use case I don't need to pay attention to the historical versions of the data table. I maintain some data tables that require some real-time updates, so there are a lot of `append` operations. In previous tests, it was found that these `append` operations produced a lot of small files in S3 storage and had extremely low IO efficiency. 

Therefore, I tried several solutions and finally found that after executing several `append`s, using `defragment_symbol_data` can generate a new large file version, and then executing `prune_previous_versions` can delete the old version of data in the `tdata` folder in S3 storage. This can effectively combine small file data into large files and release the redundant data space occupied by the old version.

But it only cleans the old version contents of `tdata` folder and `tindex` folder. The files of old versions in the `ver` folder will not be deleted, and they are very small. Although according to the principle of reading, (if I understand correctly) only the latest version of the version layer will be read, it will not cause efficiency problems in the actual use of arcticdb. But at the S3 level, so many small files will have great hidden dangers, such as creating IO bottlenecks in possible future data migration (actually we discovered this problem during my data migration process, and it made my migration becomes extremely slow and painful).

### Steps/Code to Reproduce

```python
from arcticdb import Arctic
from arcticdb_ext import set_config_int

set_config_int("SymbolDataCompact.SegmentCount", 1)

ac = Arctic(f's3://{host}:{bucket}?access={access}&secret={secret}&port={port}')
lib = ac['my_table']  # Assumed this library have experienced many append operations
symbols = lib.list_symbols()

for sym in symbols:
    if lib.is_symbol_fragmented(sym):
        lib.defragment_symbol_data(sym)
    lib.prune_previous_versions(sym)
```

Here is a reference to the code I use to do the data release. After that, when I looked at the files in the S3 file directory, the files in folder `tdata` and `tindex` are the lastest version. But the folder `ver` contains all versions from 0 to the latest version, each of which is about a few hundred bytes of small file.

### Expected Results

The files of `ver` folder should be only one for the latest version of each symbol after the process.

### OS, Python Version and ArcticDB Version

Python: 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
OS: Linux-6.2.0-36-generic-x86_64-with-glibc2.35
ArcticDB: 4.2.1

### Backend storage used

Minio S3

**Comment by alexowens90** [comment]
Hi @XiaoHuiHui233, thanks for reaching out. The maintenance of these files even when only the latest is needed is a deliberate feature of ArcticDB, and is required for "time travel" i.e. reading the data as it was at a specific point in time, although I understand this is not a feature that you require.
The private method referenced in #292 addresses this issue. As the ticket suggests, due to its private nature, this API is subject to change at any time, but we are planning to add a public method that achieves the same thing in the future. I would suggest watching this issue, so that when a supported public API method becomes available you can switch to using that.
