### ISSUE TITLE
Utilise column stats to significantly improve the performance of QueryBuilder queries

### ISSUE THREAD

**Issue by alexowens90** [man-group/ArcticDB#118]
We want to add column stats to ArcticDB data segments, enabling `QueryBuilder` to efficiently filter over columns. This will significantly improve the performance of `QueryBuilder` queries.

Sub-tasks:

- [x] #119 
- [ ] #120 
- [ ] #121 
- [ ] #122 
- [ ] #123 
- [ ] #124 
- [ ] #138 
- [ ] #125

**Comment by mehertz** [comment]
Would be good if this made a marked improvement for the use case described in #279.

**Comment by alexowens90** [comment]
Superseded by https://github.com/man-group/ArcticDB/issues/1588
