### ISSUE TITLE
xxhash hashes are non-deterministic in linux release builds

### ISSUE THREAD

**Issue by alexowens90** [man-group/ArcticDB#1268]
Original description:
In `hash.hpp` we use the macro `XXH_INLINE_ALL` for all builds except linux conda, which is more performant than `XXH_STATIC_LINKING_ONLY` which we are forced to use by this issue.

Above issue also seen in VCPKG release builds by @alexowens90 while working on #1278, so it is not purely about Conda anymore. Simultaneously, @Hind-M has also seen non-deterministic hashing behaviour even since the conda build was moved from inlining to regular static linking.

At this point, we cannot trust the results from xxhash when grouping. It is possible there are similar issues when producing hashes for atom keys from segment data, but changing these algorithms would break dedup against existing data. Propose to swap xxhash for a more reliable hasher just for grouping at this stage.

**Comment by jjerphan** [comment]
Might be related to https://github.com/Cyan4973/xxHash/issues/902.
