### ISSUE TITLE
Import from arcticdb.util.test gives an error on Windows

### ISSUE THREAD

**Issue by DrNickClarke** [man-group/ArcticDB#1279]
### Describe the bug

`from arcticdb.util.test import random_strings_of_length`

gives the error

`---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[8], line 6
      4 import random
      5 import arcticdb as adb
----> 6 from arcticdb.util.test import random_strings_of_length

File ~\Python\s3_tests\s3_tests\lib\site-packages\arcticdb\util\test.py:13
     11 import numpy as np
     12 import pandas as pd
---> 13 import pytest
     14 import string
     15 import random

ModuleNotFoundError: No module named 'pytest'
`

### Steps/Code to Reproduce

see above. Reproduced using arcticdb v4.2.1 on Windows.

### Expected Results

No error is thrown

### OS, Python Version and ArcticDB Version

Pyton 3.10, Windows 11, arcticdb 4.2.1

### Backend storage used

Does not need storage to repro

### Additional Context

The root cause is the function `param_test` https://github.com/man-group/ArcticDB/blob/master/python/arcticdb/util/test.py#L131

This function is only used by unit tests so should be moved to the unit test area of the project. Then `import pytest` can be removed from the main package.

The usages are in this file https://github.com/man-group/ArcticDB/blob/14b14b9f5f08db6f77927b517fb259095f6d341f/python/tests/unit/arcticdb/version_store/test_normalization.py#L40

**Comment by jamesmunro** [comment]
I think this was solved by your commit @DrNickClarke.
https://github.com/man-group/ArcticDB/pull/1350
Can we close?
