### ISSUE TITLE
Improve error message with recursive normalisers

### ISSUE THREAD

**Issue by DrNickClarke** [man-group/ArcticDB#1299]
### Describe the bug

When large/complex structures are stored using recursive normalisers, it fails with a confusing error that indicates that user metadata is too large. Even when the user has not specified metadata.

### Steps/Code to Reproduce

TODO

### Expected Results

The error message should state that the structure being normalised is too large/complex.

### OS, Python Version and ArcticDB Version

adb 4.0.3

### Backend storage used

On-prem S3

**Comment by jamesmunro** [comment]
@DrNickClarke Can you add steps to generate the misleading error message and a proposed improvements please?

**Comment by DrNickClarke** [comment]
Closed after moving to the internal repo here https://github.com/man-group/arcticdb-man/issues/127
