### ISSUE TITLE
Querybuilder apply multiplying by zero produces -0 and 0 values in the result

### ISSUE THREAD

**Issue by joe-iddon** [man-group/ArcticDB#1308]
### Describe the bug

With `q = q.apply('new col', q['old col'] * 0)`, there will be a mix of `0` and `-0` in the result. This is undesirable for then grouping on that column of zeros.

### Steps/Code to Reproduce

```python
>>> q = adb.QueryBuilder()
>>> q = q.apply('b', q['a']*0)
>>> l.write('s', pd.DataFrame({'a':[-1.2,1.2,3]}))
VersionedItem(symbol='s', library='l', data=n/a, version=1, metadata=None, host='MEM()')
>>> l.read('s', query_builder=q).data
     a    b
0 -1.2 -0.0
1  1.2  0.0
2  3.0  0.0
```

### Expected Results

New column consist of `0` only.

### OS, Python Version and ArcticDB Version

```
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
OS: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
ArcticDB: dev
```

### Backend storage used

LMDB

**Comment by alexowens90** [comment]
Not a real use case
