### ISSUE TITLE
Conda+mac workflow fails with MacOS version 13.6.4

### ISSUE THREAD

**Issue by joe-iddon** [man-group/ArcticDB#1322]
### Describe the bug

We request `os: macos-13` in `build_with_conda.yml` [here](https://github.com/man-group/ArcticDB/blob/5006e48db667afc171c8b44eb92a7225ff7718c3/.github/workflows/build_with_conda.yml#L101). GitHub sometimes assigns `13.6.4` or `13.6.3` (you can see from the workflow logs).

On `13.6.3`, the C++ builds fine and the tests pass, on `13.6.4` the C++ build breaks with:

```
In file included from /Users/runner/micromamba/envs/arcticdb/include/folly/container/detail/F14Policy.h:23:
/Users/runner/micromamba/envs/arcticdb/include/folly/Memory.h:77:10: error: use of undeclared identifier 'memalign'
```

Example [passing run](https://github.com/man-group/ArcticDB/actions/runs/7883878913/job/21511690661), and [failing run](https://github.com/man-group/ArcticDB/actions/runs/7880489136/job/21502608183).

This issue: https://github.com/milvus-io/milvus/issues/27464 describes the same problem which is that folly's macros don't correctly recognise that [`memalign` needs to be mapped to `posix_memalign` on macos](https://stackoverflow.com/questions/196329/osx-lacks-memalign). It attempts to notice the OS version is mac, but gets this wrong sometimes. See that issue for more details.

The fix was made to a forked version of folly (milvus-io/folly) [here](https://github.com/milvus-io/folly/pull/10/files), but only on 2023-12-11 did this get written:

> Sure, we will send the pr to folly see if they accept it

So I don't think the fix has made it to the master `facebook/folly` which is what we use. There's an issue on `facebook/folly` [here](https://github.com/facebook/folly/issues/2076) which is still open.

There's a workaround in the `facebook/folly` issue: "The solution on recent Mac versions is to downgrade CommandLineTools to 14.". We could try this to fix it.

From the logs of the runs you can click through to "Included Software". For the passing run [see here](https://github.com/actions/runner-images/blob/macos-13/20240114.1/images/macos/macos-13-Readme.md) and for the failing run [see here](https://github.com/actions/runner-images/blob/macos-13/20240204.1/images/macos/macos-13-Readme.md). They both use CommandLineTools 15, so it's unclear why one works and one doesn't.

We could try downgrading to CommandLineTools 14 if that's doable, and see if that helps?

### Steps/Code to Reproduce

NA

### Expected Results

NA

### OS, Python Version and ArcticDB Version

NA

**Comment by jjerphan** [comment]
This has been temporarily fixed with https://github.com/man-group/ArcticDB/pull/1320.

The proper medium-term solution is to adapt folly upstream directly and use the newest version.

**Comment by jamesmunro** [comment]
Closing for now.  I expect we'll see it again if it's needed.
