### ISSUE TITLE
LibraryOptions dynamic_schema=true fails to append new cols 

### ISSUE THREAD

**Issue by sambatth** [man-group/ArcticDB#134]
Even after supplying LibraryOptions dynamic_schema=true the APPEND operation fails while adding new columns. 

StreamDescriptorMismatch: The columns (names and types) in the argument are not identical to that of the existing version: APPEND 

Python 3.6, lmdb, Centos7

**Comment by markqiu** [comment]
`
from arcticdb import Arctic
from arcticdb.options import LibraryOptions
import numpy as np
import pandas as pd


ac = Arctic('s3://xxx:xxx?region=xxx&access=xxx&secret=xxx')
ac.create_library('my_data', library_options=LibraryOptions(dynamic_schema=True))

lib = ac['my_data']

NUM_COLUMNS=10
NUM_ROWS=100_000
df = pd.DataFrame(np.random.randint(0,100,size=(NUM_ROWS, NUM_COLUMNS)), columns=[f"COL_{i}" for i in range(NUM_COLUMNS)], index=pd.date_range('2000', periods=NUM_ROWS, freq='h'))

lib.write("symbol", df)

df_to_append = pd.DataFrame(np.random.randint(0,100,size=(NUM_ROWS, NUM_COLUMNS)), columns=[f"COL_{i}" for i in range(50)], index=pd.date_range('2012', periods=NUM_ROWS, freq='h'))
lib.append("mydata", df_to_append)
`

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[67], line 1
----> 1 df_to_append = pd.DataFrame(np.random.randint(0,100,size=(NUM_ROWS, NUM_COLUMNS)), columns=[f"COL_{i}" for i in range(50)], index=pd.date_range('2012', periods=NUM_ROWS, freq='h'))
      2 lib.append("mydata", df_to_append)

File ~/.conda/envs/vectorbt/lib/python3.10/site-packages/pandas/core/frame.py:757, in DataFrame.__init__(self, data, index, columns, dtype, copy)
    746         mgr = dict_to_mgr(
    747             # error: Item "ndarray" of "Union[ndarray, Series, Index]" has no
    748             # attribute "name"
   (...)
    754             copy=_copy,
    755         )
    756     else:
--> 757         mgr = ndarray_to_mgr(
    758             data,
    759             index,
    760             columns,
    761             dtype=dtype,
    762             copy=copy,
    763             typ=manager,
    764         )
    766 # For data is list-like, or Iterable (will consume into list)
    767 elif is_list_like(data):

```
File ~/.conda/envs/vectorbt/lib/python3.10/site-packages/pandas/core/internals/construction.py:337, in ndarray_to_mgr(values, index, columns, dtype, copy, typ)
    332 # _prep_ndarraylike ensures that values.ndim == 2 at this point
    333 index, columns = _get_axes(
    334     values.shape[0], values.shape[1], index=index, columns=columns
    335 )
--> 337 _check_values_indices_shape_match(values, index, columns)
    339 if typ == "array":
    340     if issubclass(values.dtype.type, str):

File ~/.conda/envs/vectorbt/lib/python3.10/site-packages/pandas/core/internals/construction.py:408, in _check_values_indices_shape_match(values, index, columns)
    406 passed = values.shape
    407 implied = (len(index), len(columns))
--> 408 raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")

ValueError: Shape of passed values is (100000, 10), indices imply (100000, 50)
```

**Comment by qc00** [comment]
@markqiu The error seems to be in your test setup?

```
ValueError                                Traceback (most recent call last)
Cell In[67], line 1
----> 1 df_to_append = pd.DataFrame(np.random.randint(0,100,size=(NUM_ROWS, NUM_COLUMNS)), columns=[f"COL_{i}" for i in range(50)], index=pd.date_range('2012', periods=NUM_ROWS, freq='h'))
...
ValueError: Shape of passed values is (100000, 10), indices imply (100000, 50)
```

I.e it should have been `size=(NUM_ROWS, 50)`

**Comment by jamesmunro** [comment]
We think this works.  Closing.
