### ISSUE TITLE
What is the Python requirement?

### ISSUE THREAD

**Issue by arman-zhumakhan** [man-group/ArcticDB#135]
When I tried to install ArcticDB using Python 3.10, I got this error
`ERROR: Could not find a version that satisfies the requirement arcticdb (from versions: none).`
`ERROR: No matching distribution found for arcticdb`

3.10 should be supported according to the documentation. I don't know if this issue is related to the Python version

**Comment by mehertz** [comment]
Hi @arman-zhumakhan 

ArcticDB works across Python 3.6-3.10 (inclusive) - however _only on Linux_. This restriction is only mentioned on the GitHub readme currently. 

Just to check, are you installing on Linux?

**Comment by arman-zhumakhan** [comment]
Sorry, I missed this point. I tried it on Windows. Thanks for your reply.

**Comment by qc00** [comment]
We're pleased to announce [v1.1.0](https://github.com/man-group/ArcticDB/releases/tag/v1.1.0) has been released to [Pypi](https://pypi.org/project/arcticdb/) with Windows builds.
