### ISSUE TITLE
Add read_index to LibraryTool API

### ISSUE THREAD

**Issue by poodlewars** [man-group/ArcticDB#1391]
We have an internal method `lib._nvs.read_index` to describe the on-disk structure of a symbol. Some users find it helpful. It would be good to move it to the LibraryTool API, and add documentation for how to use it and interpret its output. While we're at it we should put some of the other library tool methods on the guide.

We should make it clear that we don't offer API guarantees for the LibraryTool and have plenty of caveat emptor warnings.

**Comment by muhammadhamzasajjad** [comment]
Regarding documentation, it was discussed that for now we are going to leave the docstrings. Later, we might add LibraryTool to the docs-website.
