### ISSUE TITLE
Update deletes symbols starting with same name as symbol being updated

### ISSUE THREAD

**Issue by jdry1729** [man-group/ArcticDB#1398]
### Describe the bug

Suppose I write data to a symbol "abc/def" and then to "abc". The symbol "abc/def" gets deleted. This shouldn't happen.

### Steps/Code to Reproduce

```python
>>> lib.write("abc/def", pd.Series([1, 1, 1], index=pd.date_range("2024-01-01", "2024-01-03")))
>>> lib.read("abc/def").data # shows data

>>> lib.write("abc", pd.Series([1, 1, 1], index=pd.date_range("2024-01-01", "2024-01-03")))
>>> lib.read("abc").data # shows data

>>> lib.read("abc/def") # throws NoSuchVersionException
```

### Expected Results

The symbol "abc/def" shouldn't be deleted.

### OS, Python Version and ArcticDB Version

Python 3.9.17
ArcticDB 4.0.1

### Backend storage used

Minio (S3)

**Comment by vasil-pashov** [comment]
Hi thank you for reporting an issue. This is not reproducible with the latest version of ArcticDB. Our suggestion is to switch to v4.3.1
