### ISSUE TITLE
search by meta data

### ISSUE THREAD

**Issue by RockScience** [man-group/ArcticDB#141]
Hello,

is there an efficient way to retrieve the list of symbols that have a specific meta data value?

At the moment I have to loop over all symbols and call lib.read_metadata, that doesnt seem very efficient.
For instance below get all symbols from _my_library_ that have meta data **_color=="blue"_**

    def find_symbol_by_metadata(library, metadata, value):
      selected_symb = []
      for symbol in library.list_symbols():
        md = library.read_metadata(symbol=symbol).metadata[metadata]
        if (md == value):
          selected_symb.append(symbol)
      return(selected_symb)

then 
      
`find_symbol_by_metadata(library=store['my_library'], metadata='color', value="blue")`

**Comment by RockScience** [comment]
Could it be possible for instance to have `read_metadata` accept a list? Or even by default return meta data from all symbols of the library if we dont pass any symbol in argument?

**Comment by mehertz** [comment]
Created #143 to reflect this. Please feel free to contribute the change if you can - well be a case of calling into the underlying `self._nvs.batch_read_metadata` method.
