### ISSUE TITLE
Error using arm64V8

### ISSUE THREAD

**Issue by aTGuz** [man-group/ArcticDB#144]
Hi there: 

Can I run arcticDb over arm64 arch? 
I tried to do it but received an error.

**Comment by mehertz** [comment]
Hi @aTGuz 

We don't have an ARM build and it's not on our short-term roadmap. 

When you say you tried, do you mean you tried compiling against ARM?

**Comment by mehertz** [comment]
Hi.

Please see this link for detailed build instructions:

https://github.com/man-group/ArcticDB/blob/master/docs/mkdocs/docs/technical/contributing.md

Any issues/difficulties, let us know.
