### ISSUE TITLE
Add mypy to build

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#146]
* Would be nice to type-check Python

**Comment by poodlewars** [comment]
And C++ linter while we're at it?

**Comment by jjerphan** [comment]
Hi,

I guess [pre-commit](https://pre-commit.com/) provides all the hooks that ArcticDB might need. Would you be interested in setting up such a setup with this tool?

**Comment by jjerphan** [comment]
To you, is https://github.com/man-group/ArcticDB/pull/445 a complete solution to this issue?

**Comment by qc00** [comment]
No, it's doesn't have mypy?

**Comment by mehertz** [comment]
I'm renaming to just mention mypy
