### ISSUE TITLE
Clarify license in README

### ISSUE THREAD

**Issue by harry-xm** [man-group/ArcticDB#1480]
**Is your feature request related to a problem? Please describe.**
README describes the license as "users may not use ArcticDB for production use or for a Database Service", but the LICENSE.txt file grants limited production use with only one restriction (i.e. not for a "Database Service").

**Describe the solution you'd like**
Be consistent in licensing terms.

**Describe alternatives you've considered**
N/A

**Additional context**
None.

**Comment by athakur91** [comment]
Hi @harry-xm thank you for raising, I'm looking into how we could improve the language to be clearer.

In the meantime if you wanted to discuss please do feel free to reach out on email arcticdb@man.com very happy to help

Thanks!

**Comment by athakur91** [comment]
hi @harry-xm no changes made so far but hopefully this section on our licencing FAQs helps clarify:

https://docs.arcticdb.io/latest/licensing/ 

If you'd like to discuss please do let me know I can be reached directly at arcticdb@man.com

**Comment by athakur91** [comment]
Hi @harry-xm thanks for the further details. I appreciate you raising and appreciate that it could be clearer. We wrote our licence and readme with legal advice. We're looking into this.
