### ISSUE TITLE
python 3.12 support

### ISSUE THREAD

**Issue by endir** [man-group/ArcticDB#1535]
I would like to use arcticdb with python 3.12. It seems that it is not supported at the moment. 
If this is wrong how can I build arcticdb from source? Do you plan to support python3.12 ?

**Comment by poodlewars** [comment]
Python 3.12 support is covered by #1230 which we do plan to implement.

It _might_ work if you build from source:

```
# activate Python 3.12 venv
python setup.py bdist_wheel
# then auditwheel repair the built wheel
```
