### ISSUE TITLE
Can't access index in `QueryBuilder` query

### ISSUE THREAD

**Issue by Naich** [man-group/ArcticDB#157]
Is it possible to reference data indices using QueryBuilder , similar to how columns are referenced with q['column_name']?

This would make it easier to perform operations such as time-based slicing/groupby(currently not supported yet) and other manipulations that require indexing specific data points.

**Comment by alexowens90** [comment]
In short, yes it is.
If you have explicitly named your (multi-)index, then you can filter on them like any other column. See this [test](https://github.com/man-group/ArcticDB/blob/master/python/tests/unit/arcticdb/version_store/test_filtering.py#L1534-L1545) for an example.
If not, then there are some "hidden" names we use to refer to index columns, and that you can use to refer to them in the `QueryBuilder`.
If it is a single index, then it will be named `index`.
If it is a multiindex, then the levels will be named `__fkidx__n` where `n` is the level of the index (0, 1, 2, etc).

Note that any filtering that can be achieved using the `date_range` parameter to `read` will be much more efficient than using the `QueryBuilder`, as `date_range` uses information from the index layer in our data storage model, whereas the `QueryBuilder` will always check every index value.

**Comment by qc00** [comment]
We have an issue to provide a proper/supported API: #222

**Comment by mehertz** [comment]
We should:

- [ ] Expose index columns officially
- [ ] Document how to do this

**Comment by mehertz** [comment]
Renmaed to better reflect the question.

**Comment by mehertz** [comment]
@alexowens90 comment should provide a workaround. You can track the ongoing work to make this clearer in #222, so will close this ticket.
