### ISSUE TITLE
Does ArcticDB support Chinese?

### ISSUE THREAD

**Issue by myvrml** [man-group/ArcticDB#1582]
I found I can write a table have column in Chinese, but programe is dead(without any exception or error) when append data in table.

I like ArcticDB and wish it can support Chinese!

**Comment by DrNickClarke** [comment]
Thank you for reporting this to us. Would it be possible to provide a repro case to help us get the the specific issue fast?

**Comment by DrNickClarke** [comment]
Actually we recently fixed an issue that might be the one you are seeing. Please try again with version 4.4.3rc0 (which is on pypi) and let us know if that fixes your problem.
