### ISSUE TITLE
Revert pin to VS 17.9.7 from #1611 when GH runner image is updated

### ISSUE THREAD

**Issue by muhammadhamzasajjad** [man-group/ArcticDB#1613]
New release of GH runner image 20240603.1.0 lead to CI failures on windows. This was due to VS toolset update https://github.com/actions/runner-images/issues/10004. This should be reverted once a new image is released which fixes the issue.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by maxim-morozov** [comment]
This was reverted
