### ISSUE TITLE
Feature to restrict versions of a symbol to only the previous and latest one.

### ISSUE THREAD

**Issue by philsv** [man-group/ArcticDB#1628]
**Is your feature request related to a problem? Please describe.**
For my usecase I really only want maximum 2 versions of a symbol saved in a library.

I tried prune_previous_version=True but still on some symbols data I do have 90+ versions which I really don't need.
Since I started using articdb I have always appended my data, which I guess will always create a new version?
Should I use update instead, will this solve my problem? I can't find reliable information in the docs or in the code.

**Describe the solution you'd like**
Where I can use something like that:
```
library.append(symbol, keep_latest_versions=2)
library.update(symbol, prune_previous_versions=True)
```
And it reliably only holds the previous version and the latest version, and removes any other versions related to the symbol.

**Describe alternatives you've considered**

**Additional context**
Is there another way to achieve that or simular results?

**Comment by jamesmunro** [comment]
Hi,

I expect you are seeing that `prune_previous_versions` wasn't behaving as expected on `append` and `update`.  We have a proposed fix in PR: https://github.com/man-group/ArcticDB/pull/1640/files

Would this solve your use case? Or you would like further flexibility like this as well?

**Comment by philsv** [comment]
Hi @jamesmunro,

that would be amazing if `prune_previous_version` works on both append and update. 

So if I understand this correctly this:
`Removes previous (non-snapshotted) versions from the database.`

will remove all versions except from the latest (latest timestamp) by applying prune_previous_version if this PR gets merged?
If so, yes this would be enough for my use case.

**Comment by jamesmunro** [comment]
Yes, that's exactly right.  We're definitely proceeding with this fix so I'll close this request.   Please note that the first run with the new version (detail will be in the release notes) may run slower as it does an initial prune.
