### ISSUE TITLE
LMDB windows, error when access with newly created library.

### ISSUE THREAD

**Issue by Shadow-Alex** [man-group/ArcticDB#1673]
### Describe the bug

Hi, I have a old arcticDB setup on LMDB windows. There is a working library which I can access via
```python
import arcticdb as adb
ac = adb.Arctic('lmdb://D://arcticDB?map_size=1024GB')
lib = ac['intraday_ohlcv']
```

However I cannot create new library now. while the old library is still accessible.
```python
import arcticdb as adb
ac = adb.Arctic('lmdb://D://arcticDB?map_size=1024GB')
ac.create_library('test')
```

the above lib creation code result in a Traceback error:
```python
  File "E:\anaconda3\envs\quant\lib\site-packages\arcticdb\arctic.py", line 217, in create_library
    return self.get_library(name)
  File "E:\anaconda3\envs\quant\lib\site-packages\arcticdb\arctic.py", line 153, in get_library
    lib = self[name]
  File "E:\anaconda3\envs\quant\lib\site-packages\arcticdb\arctic.py", line 99, in __getitem__
    self._library_manager.get_library(lib_mgr_name, storage_override),
arcticdb_ext.exceptions.InternalException
```

I dont really know if the lib is created or not, I think its a bug halfway, as I manage to list the library after the unsuccessful creation.
```python
ac.list_libraries()
```
![image](https://github.com/man-group/ArcticDB/assets/46802674/1de6316a-963f-4ea9-9eba-4c317b5a1db9)

### Steps/Code to Reproduce

```python
import arcticdb as adb
ac = adb.Arctic('lmdb://D://arcticDB?map_size=1024GB')
ac.create_library('test')
```

### Expected Results

successfully created.

### OS, Python Version and ArcticDB Version

Python: 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:24:38) [MSC v.1916 64 bit (AMD64)]
OS: Windows-10-10.0.19045-SP0
ArcticDB: 4.4.3

### Backend storage used

LMDB

**Comment by alexowens90** [comment]
Hi @Shadow-Alex, thanks for raising, I just need a few more details:

- Is there an exception message associated with the `InternalException`? If so, it would be useful for me to see what it says.
- I assume the ArcticDB version (4.4.3) you've mentioned is the version which you're seeing the error with?
- You mentioned that your ArcticDB setup is "old", what version were the other libraries created with?
