### ISSUE TITLE
Installation of arcticdb package not working on anaconda prompt

### ISSUE THREAD

**Issue by shukai-lu-int** [man-group/ArcticDB#1707]
### Describe the bug

I have tried multiple versions of

$ conda install arcticdb

and it still seems like the anaconda prompt does not recognize arcticdb from conda-forge. Any reason why? I must be missing something obvious.

![Uploading image.png…]()

### Steps/Code to Reproduce

$ conda install arcticdb

### Expected Results

The package should be successfully installed.

### OS, Python Version and ArcticDB Version

conda 24.5.0
python 3.12.3

**Comment by poodlewars** [comment]
We don't have a Python 3.12 build yet. The maximum Python we support is 3.11.
