### ISSUE TITLE
Assume fast_tombstone_all is set when deleting data

### ISSUE THREAD

**Issue by GemDot** [man-group/ArcticDB#174]
When deleting data, either a `tombstone` or a `TOMBSTONE_ALL` key will be written. 

Whilst we need to respect either key type when reading data (for backwards compatibility reasons), there is no longer any reason to _not_ write `TOMBSTONE_ALL` keys. 

This change will require simplifying the flow for deleting data to remove any code branches that would execute should `fast_tombstone_all` be off.

**Comment by vasil-pashov** [comment]
PR: #366
