### ISSUE TITLE
Series normalizer converts empty series name to None

### ISSUE THREAD

**Issue by vasil-pashov** [man-group/ArcticDB#1841]
### Describe the bug

When a series is stored into ArcticDB and the name of the series is empty string it gets converted to `None` on read.

### Steps/Code to Reproduce

```python
import pandas as pd
import numpy as np
import arcticdb as adb

ac = adb.Arctic("lmdb://test")
lib = ac.get_library("test", create_if_missing=True)

series = pd.Series(data=[1], index=pd.DatetimeIndex([pd.Timestamp(2024, 1, 1)]), name='')
print(type(series.name)) # <class 'str'>
lib.write("sym", series)
res = lib.read("sym").data
print(type(res.name)) # <class 'NoneType'>
```

### Expected Results

Keep the name the series an empty string

### OS, Python Version and ArcticDB Version

Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
OS: Windows-10-10.0.22631-SP0
ArcticDB: 4.5.0

**Comment by alexowens90** [comment]
Fix was buggy, reverted in #1953
