### ISSUE TITLE
MacOS Apple Silicon PyPi build

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#187]
We have a MacOS x86 & Apple Silicon build for [Conda](https://anaconda.org/conda-forge/arcticdb/files). As a result there aren't any fundamental issues that will prevent the build. Note that this ticket corresponds to the Apple Silicon build - I don't believe MacOS x86 is worth targetting any more. 

However, Conda and PyPi builds are distributed differently. The PyPi build is largely statically linked which will likely mean more work will need to be done to get a clean build for MacOS.

We'll also need to investigate the Apple Silicon runners available on GitHub.

**Comment by mehertz** [comment]
@qc00 do you know of any build blockers for this?

**Comment by qc00** [comment]
I have never tried, but some potential ones:

* Dependencies missing/not fully patched in `vcpkg`
* MacOS typically uses `.dylib`. I am not sure if we can distribute a `.so` in wheels. 
* Different handling for external lib dependencies (i.e. `auditwheel` -> `delocate`)
* There's not enough GitHub Actions cache space to hold yet another OS's build

**Comment by jjerphan** [comment]
Apple M1 macOS runners are now available on GitHub actions.

See https://github.com/actions/runner-images/issues/8439

**Comment by poodlewars** [comment]
Duplicates #759
