### ISSUE TITLE
Prevent out-of-order data being written unless explicitly requested

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#188]
Currently, ArcticDB lets you write out-of-order data without making it clear that this will cause the `date_range` keyword-argument to fail.

_write_, _update_ and _append_ should all follow the same behaviour:

All methods should be modified to raise an exception should the user be writing data with a _sortable_ index but where the data itself is unsorted.

If the user genuinely wants to write unsorted data, they should be forced to pass in a keyword argument as `False`: `ensure_sorted`.

There are two APIs in ArcticDB; `_store.py` and `library.py`. The logic for this change should be specified in the C++ such that we can support differing behaviour in the two Python APIs.

`ensure_sorted` should default to `True` for `library.py` and `False` for `_store.py`. This is to ensure backwards compatibility with users of `_store.py`. 

Note: For `update`, in addition to the above changes, we should reject operating on data that is known not-sorted (so `UNSORTED`). 

We should also provide a friendly error message should the user pass in a `date_range` query for data that is either not datetime-indexed or for data that is datetime-indexed but is known unsorted.

- [x] Add `ensure_sorted` to `write`, `append`, and their `batch_` equivalents
- [x] Set `ensure_sorted` to `True` in `library.py` and `False` to `_store.py`
- [x] If `ensure_sorted` is true, raise an exception if the input data is a) datetime index and b) not sorted. Ignore if not datetime index.
- [x] Prevent `update` on datasets that are known not-sorted
- [x] Prevent `update` on non-datetime indexed data
- [x] Document (docstring) `ensure_sorted`
- [x] Provide a friendly error message **on read** should the user pass in a `date_range` query for data that is either not datetime-indexed or for data that is datetime-indexed but is known unsorted.

**Comment by qc00** [comment]
> We should also provide a friendly error message should the user pass in a date_range query for data that is either not datetime-indexed or for data that is datetime-indexed but is known unsorted.

Can we split this behaviour by library type as well? `library.py` don't _have_ to be backwards-compatible with Arctic.
