### ISSUE TITLE
facility to change default size of library in LMDB on windows

### ISSUE THREAD

**Issue by bh-nil** [man-group/ArcticDB#1882]
**Is your feature request related to a problem? Please describe.**
currently whenever I create a library in arctictDb on windows using LMDB, it takes up 2 gb of space.  this unnecessorily eat up space.

**Describe the solution you'd like**
best solution is to implement lazy space allocation as it is doing in linux environment. else please provide facility to specify default size.
I am hoping that in case of default 2gb size, it automatically increase size if data is more than 2gb on windows platform

**Comment by poodlewars** [comment]
You can use the `map_size` - https://docs.arcticdb.io/latest/api/arctic_uri/#lmdb 

It is not possible to implement the lazy space allocation on Windows - this is an intrinsic behaviour of LMDB on Windows that we have no control over.
