### ISSUE TITLE
Improve error code handling - add error codes for `*NotFound` and networking errors

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#191]
- [x] Write a test to ensure C++ exceptions can be caught in Python (believe this to already be the case)
- [x] Display error code in python error message
- [x] Ensure all `not found` errors have known error codes (for example - library/symbol not found)
- [x] Ensure that S3/network errors - being unable to write all have a defined error category
- [x] Ensure `streamid` isn't revealed in the error messages
- [x] Update the docs

**Comment by phoebusm** [comment]
@mehertz For task 5, how about logging?
