### ISSUE TITLE
multiprocessing: parallel reads, dramatic performance degradation backend: lmdb

### ISSUE THREAD

**Issue by buhbuhtig** [man-group/ArcticDB#194]
I use ray (ray.io) for parallel computing (32 cores). In each process, I run a separate algorithm that accesses arcticdb (backend: lmdb) and reads the data. I found a dramatic performance drop (1000-10000x slower) on parallel reads (race conditions?). I partially solved the problem by using global mutex, so that only one process can read from arcticdb (backend: lmdb) at any given time. And so, the question is: is parallel (multiprocessing) reading from arcticdb with lmdb backend allowed? If yes, what could be the problem with the performance drop?
Thanks

Ubuntu 20.04

**Comment by qc00** [comment]
We mainly expect our users to use S3 and LMDB is meant for small-scale local testing. However, we are having some unexpected performance difficulties with LMDB in our tests as well, so an unintended lock must have been introduced somewhere.

We will likely resolve this in due course.

**Comment by jjerphan** [comment]
Hi @buhbuhtig,

Thank you for this report. Could you [craft a minimal reproducer](https://matthewrocklin.com/minimal-bug-reports) for the behavior you report?

If your report appears to be dependent on external data files and cannot be reproduced without them, please describe your data files in as much detail as you can.

Also, if the code is too long, feel free to put it in a [public gist](https://gist.github.com/) and link it in this issue.

We acknowledge that this requires some effort from you, but it really helps us locate the problem and we thank you for helping us out.

**Comment by poodlewars** [comment]
Hi @buhbuhtig we have made a lot of changes to our LMDB integration in the `1.6.0` release. Please could you test with that and let us know if there is any improvement?
