### ISSUE TITLE
datetimes in get_description returned are naive when they should be timezone-aware.

### ISSUE THREAD

**Issue by reggied** [man-group/ArcticDB#197]
[get_description](https://docs.arcticdb.io/api/library/arcticdb.version_store.library.Library?highlight=get_description#arcticdb.version_store.library.Library.get_description) claims to return a [SymbolDescription](https://docs.arcticdb.io/api/library/arcticdb.version_store.library.SymbolDescription.html#arcticdb.version_store.library.SymbolDescription) where last_update_time and date_range are UTC times, but the datetime objects returned have no tzinfo that indicates they are UTC datetimes.

**Comment by qc00** [comment]
Related (but not necessarily have to be tackled together): #189

**Comment by mehertz** [comment]
Fixed @reggied
