### ISSUE TITLE
list_versions is very slow for a large number of versions.

### ISSUE THREAD

**Issue by reggied** [man-group/ArcticDB#198]
list_versions is extremely slow for a large number of versions. E.g. for a single symbol that has 5000 versions, it takes over 6 minutes for list_versions to complete. Could this be made more efficient?

**Comment by mehertz** [comment]
Hi @reggied .

They key to this is to compact the version map frequently - currently this has to be invoked manually though depending on use case can be moved inline. This effectively transforms the linked list on storage into a single node, transforming potentially hundreds of required IOs to just one. 

For now, you can manually invoke this using the following method:

```
lib._nvs.version_store._compact_version_map(<SYMBOL NAME>)
```

After running that, `list_versions` should be quick. You can run this after each `write`/`append`, but that will slow down the write operation. Might be worth running every 20/30 writes to amortize the cost. 

Apologies for the ugly method API path - can tidy that up after you've confirmed that achieves the desired result.

**Comment by reggied** [comment]
Thanks for the explanation @mehertz . Would it make sense to periodically trigger this in the background? When the `list_versions` is called, is compaction done automatically?

**Comment by Chen-Oliver** [comment]
Compaction on 5000 versions took around 6 minutes to complete, but `list_versions` is now much faster and takes <1s compared to the previous 6-7 minutes.

I repeated the compaction experiment after every 20 writes to the symbol and each compaction took 1-2s and the time to `list_versions` appears to hover around ~1s.

Would there be any issues if compaction is done while the symbol is being written to/read from?
Does it make sense for us to be triggering this compaction or should Arctic know to do it periodically?

**Comment by qc00** [comment]
`_compact_version_map` is designed to only rewrite on version keys before the current version, so it is safe to run concurrently with write/append operations. It may cause the read of a historical version to transiently fail. It cannot run concurrently with delete operations.

All above assumes the backing storage supports [strong consistency](https://aws.amazon.com/s3/consistency/).

**Comment by mehertz** [comment]
Hi. I'm going to close this as we have created #292 to monitor the work to make it in inline operator called when writing data. If your workaround (manually calling compact) isn't sufficient happy to re-open.
