### ISSUE TITLE
OutOfBoundsDatetime error occurring with open-ended date range

### ISSUE THREAD

**Issue by reggied** [man-group/ArcticDB#201]
According to the API documentation, the read method should accept date ranges in the format of (None, end_date) and (start_date, None). However, when attempting to use the library.read() method with the argument date_range=(None, end_date), it results in an exception being raised.

The error message indicates that the issue lies with the `start_val` argument, which is converted to a UTC timestamp using the `_to_utc_ts()` function. In this case, the `start_val` argument is `None`, resulting in a call to `pytz.utc.localize(Timestamp.min)`, which generates an _OutOfBoundsDatetime_ exception with a timestamp of 1677-09-21 00:12:43.

**Exception:**
…
```-> 1285     s = _to_utc_ts(start_val, "start") if start_val else pytz.utc.localize(Timestamp.min)```
…
OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1677-09-21 00:12:43

**Comment by qc00** [comment]
I believe this is a dup of #88.

**Comment by reggied** [comment]
Closed as duplicate of #88
