### ISSUE TITLE
How to solve slow write speed?

### ISSUE THREAD

**Issue by weepo-bean** [man-group/ArcticDB#2030]
I created an LMDB on my local hard drive, and after using it for a while, why did my write speed become very slow, while my read speed remained fast? What should I do to resolve this issue? There are two things to note: the free space on my hard drive has decreased, but there is still over 200 GB available; and I only created one library, and I frequently delete some tables within it and then create new tables with the same name and insert or modify the new data. However, the total data volume has not changed significantly.

**Comment by alexowens90** [comment]
Hi @weepo-bean, can you please provide all of the information specified in the bug report form?
https://github.com/man-group/ArcticDB/issues/new?assignees=&labels=bug&projects=&template=bug_report.yaml
