### ISSUE TITLE
Are there any useful visualization tools for ArcticDB?

### ISSUE THREAD

**Issue by WANGYE-2012** [man-group/ArcticDB#2040]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by WANGYE-2012** [comment]
Are there any useful visualization tools for ArcticDB?

**Comment by alexowens90** [comment]
What exactly are you trying to visualise? For visualising dataframes stored in ArcticDB, we integrate with [dtale](https://github.com/man-group/dtale)

**Comment by WANGYE-2012** [comment]
Similar to Studio 3T of mongodb.

**Comment by WANGYE-2012** [comment]
Similar to DBeaver.

**Comment by alexowens90** [comment]
Then no, nothing like that exists for ArcticDB right now
