### ISSUE TITLE
QueryBuilder filter and aggregation cannot co-exist in one syntax

### ISSUE THREAD

**Issue by Naich** [man-group/ArcticDB#206]
When attempting to perform a groupby operation on a filtered QueryBuilder, ArcticDB throws an "E_ASSERTION_FAILURE Field XXX not found in aggregation" error, followed by a "Segmentation fault (core dumped)" error.

I was unable to find any information in the documentation regarding whether this operation is supported. 
In unit test code, test_aggregation and test_filter were seperated.
Is this error expected behavior? Are there any plans to support filter-then-groupby in the future?

BTW:  agg and then filter worked fine.

Example code:
```
data = {'COL_1': {0: 1, 1: 2, 2: 3, 3: 4, 4: 1, 5: 2, 6: 3, 7: 4},
 'COL_2': {0: 'A', 1: 'A', 2: 'B', 3: 'B', 4: 'C', 5: 'C', 6: 'D', 7: 'D'}}
lib.write("test", pd.DataFrame(data))

from arcticdb import QueryBuilder
q = QueryBuilder()
q = q[q['COL_1'] >= 0] #q_filter
q = q.groupby('COL_2').agg({"COL_1":"max"}) #q_agg
lib.read("test",  query_builder=q).data
```

Error output:
> [2023-04-06 16:03:32.514] [arcticdb] [error] E_ASSERTION_FAILURE Field COL_1 not found in aggregation
> [2023-04-06 16:03:32.514] [arcticdb] [error] E_ASSERTION_FAILURE Field COL_1 not found in aggregation
> [2023-04-06 16:03:32.514] [arcticdb] [error] E_ASSERTION_FAILURE Field COL_1 not found in aggregation
> Segmentation fault (core dumped)

**Comment by alexowens90** [comment]
I'm able to reproduce this with the example given.
The plan long term is to support combined filters, projections, and groupbys with the syntax provided in the example. However, these code paths are currently untested, and so are not expected to work right now.

**Comment by Naich** [comment]
@alexowens90 
Thank you so much for taking the time to reproduce the error and share future development plans for the project. I truly appreciate it and look forward to seeing further updates on this issue.

Regarding the issue of error handling, maybe firstly we should try to avoid segmentation faults. Perhaps it would also be helpful to include a reminder in the QueryBuilder documentation.

**Comment by mehertz** [comment]
Agreed! I think first port of call is to ensure that QueryBuilder syntax raises prior to it being passed to `read` to prevent the segmentation fault and to update the documentation.

After that we should just fix this - it _should_ work.
