### ISSUE TITLE
Writing 0-row DataFrame: correctness and usability

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#224]
As exposed by `test_normalization.py::test_store_df[empty_midx]`

Internal thread: $.slack.com/archives/C02NEG3V38X/p1678796229175589

Pandas (rightly) changed the default type of a 0-row index to `object` which (rightly) triggers a normalization error:

> ArcticNativeNotYetImplemented: coercing column type is required when empty column of object type, Column type=object for column=...

1. Should provide guidance in the error message to explicitly set the type of the index OR special handling to allow it

2. Due to #223, above exception actually cause 0-row DF to be pickled

**Comment by phoebusm** [comment]
Is it related to https://github.com/man-group/ArcticDB/issues/90?

**Comment by qc00** [comment]
Yes, #90 is a dup of point 2 above.

**Comment by jjerphan** [comment]
> Should provide guidance in the error message to explicitly set the type of the index OR special handling to allow it

I think users should not have to set it manually, and ArcticDB rather has to identify such case and coerce those empty `pd.Series` and `pd.DataFrame` to a relevant representations.

For empty column, we could change the newly used `dtype=object` to the previously used `dtype=float`, yet we might or will be blocked if other items than `float` are appended to the column (see https://github.com/man-group/ArcticDB/pull/540#discussion_r1265126115 which discusses it).

Is there a way to change the type of an (empty) column?

**Comment by qc00** [comment]
> Is there a way to change the type of an (empty) column?

That's the crux of the problem. The current stream descriptor handling does not allow column type change (apart from mixing numerical types under dynamic schema).

We would need to change the C++ to support a special undefined type that can be changed into any other type in a subsequent data key.

**Comment by willdealtry** [comment]
The changes that @vasil-pashov are moving over to support Decimals, numpy arrays etc will introduce a new NoneType which is promotable to anything, I suggest we wait until those are merged and then see if they do what we need for this case.

**Comment by jjerphan** [comment]
Empty `pandas.DataFrame` and empty `pandas.Series` columns types might be set differently by Pandas depending on its version. They are generally also reset by pandas if the users provide them at creation.

Shouldn't there be a way to have users explicitly provide types for a symbol's schema to one of ArcticDB's API, be it a backed by an empty `pandas.DataFrame` or an empty `pandas.Series`, rather than automatically assuming the types of the schema without being able to guess if they have been provided by users or changed by Pandas in between?

**Comment by jjerphan** [comment]
Can this issue be closed as completed as explained in https://github.com/man-group/ArcticDB/issues/90#issuecomment-1727387284, or is there anything left to do?

**Comment by poodlewars** [comment]
Closing this, I think #91 covers the outstanding part. Besides that we have a proper "empty" type now
