### ISSUE TITLE
WarnVersionTypeNotHandled log is confusing when seen from add_to_snapshot call

### ISSUE THREAD

**Issue by alexowens90** [man-group/ArcticDB#228]
There may be other API methods that trigger this log as well that are not batch read.

**Comment by mehertz** [comment]
An example of the logs would be helpful if you have it handy.

**Comment by muhammadhamzasajjad** [comment]
@alexowens90, is this bug still relevant? If yes, could you please provide more context and the code for reproducing this issue?
