### ISSUE TITLE
Ensure complex data structures can be printed during debug

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#232]
We should ensure protobuf, BitMagic, etc. can be printed from any source file (at least in the DEBUG build).

Some ideas:

- [ ] Ensure `fmt::print()` is compiled in for these types
- [ ] Use a compiler parameter to load a debug helper header in every compilation unit, so `fmt::format`, etc. can be found
- [ ] Declare some global vectors of various common types so it's possible to evaluate expressions that need to allocate memory
- [ ] Ensure `std::get<>` is available (in the debug helper header) for all types in all `variants`

**Comment by mehertz** [comment]
This doesn't feel that critical right now. I'm inclined to close as I don't think we're going to schedule this work for a very long time.
