### ISSUE TITLE
Wheel build dominated by compiling ancient grpcio-tools

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#234]
Due to #226, we're using `grpcio_tools-1.29.0` for Protobuf 3 and due to its age, it has no pre-built binary for recent Python versions.

`pip` will have to compile it from scratch on every build, which takes 6-10mins in an 8-10mins wheel build.

We should pre-compile it and install our own wheel.

**Comment by poodlewars** [comment]
Worth considering the alternative of upgrading Man's protobuf version internally and simply using a newer grpcio-tools
