### ISSUE TITLE
Pandas 2.0 support

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#237]
- [x] `The frame.append method is deprecated and will be removed from pandas in a future version`
- [ ] Decide on #224 
- [ ] Change `setup.cfg` and `environment_unix.yml` to depend on any version rather than < 2

We should also start treating pytest warning outputs more seriously

**Comment by mehertz** [comment]
We need to remove the dependency on `Pandas < 2.0`

**Comment by jjerphan** [comment]
pandas 2.0 might be required for the full support of Apache Arrow (#165): in addition to bug-fixes and performance improvements related to pyarrow, [pandas 2.0 also introduced support for pyarrow-backed nullable dtypes](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html#argument-dtype-backend-to-return-pyarrow-backed-or-numpy-backed-nullable-dtypes).
