### ISSUE TITLE
Row-slicing with date_range only by segments.

### ISSUE THREAD

**Issue by sharp2448** [man-group/ArcticDB#243]
Firstly, great job with ArcticDB! Had been using also it's predecessor Arctic, but I'm facing an issue that seems strange to me. Can't figure out if it's a bug or by design.

I'm using ArcticDB to store OHLCV data i in `DataFrame` with `DatetimeIndex`.
#### Platform and version
OS: Arch Linux 
Kernel: 6.2.11-arch1-1
Python 3.10.11

Same also in docker:[ python:3.10.11-slim](https://hub.docker.com/layers/library/python/3.10.11-slim/images/sha256-89648909125f37eeff6dee35491e6295c77b76c42aa1aff2523478990e73d3fe?context=repo&tab=vulnerabilities)

#### Can't retrieve entire date_range
My problem is that when i'm trying to read and slice the dataframe with `date_range` it only returns a subset of the `date_range` that fits into the segment. I need the entire requested `date_range`, not just a subset that fits into the segment. 

**This is my code**:
The `start` variable is assigned a datetime object with the date and time January 1st, 2022 at 1:15 PM, while the `end` variable is assigned a datetime object with the date and time February 20th, 2023 at 9:45 AM.
```python
start=datetime.datetime(2022,1,1,13,15,00)
end = datetime.datetime(2023,2,20,9,45,00)

df=lib2.read(symbol,date_range=(start,end)).data
print(start,end)
df
```
  
**This is what is returned by `df`:**
<img src="https://user-images.githubusercontent.com/30528303/233013289-3d343464-f5dd-45c4-b168-81b2c877b199.png"  width="600" height="400">
Notice the start and end dates (what date range I get in DF and the rows number). I also tried using `pd.Timestamp` instead of datetime, no luck... in another words, it looks that i can only slice dataframe by segments.    

**Info about the DataFrame**
```
<class 'pandas.core.frame.DataFrame'>

DatetimeIndex: 1328556 entries, 2023-04-12 17:17:00 to 2020-09-11 07:42:00

Data columns (total 6 columns):

 #   Column  Non-Null Count    Dtype  

---  ------  --------------    -----  

 0   volume  1328556 non-null  float64

 1   open    1328537 non-null  object 

 2   close   1328542 non-null  object 

 3   high    1328418 non-null  float64

 4   low     1328556 non-null  float64

 5   time    1328556 non-null  int64  

dtypes: float64(3), int64(1), object(2)

memory usage: 71.0+ MB
```

The dataframe is not corrupt since I can slice it once it's out of DB easily by `df[start:end]`

Also I didn't have this issue with the predecessor Arctic, but it would make no sense if this was by design... unless im missing something? Appreciate any help!

**Comment by bulltools** [comment]
@qc00 nice timing - thanks for the reference ill go over it now

what do you mean by not fully sorted? im storing time series data, but there are gaps in the data for low volume symbols. could it be the cause of the problem?

**Comment by qc00** [comment]
@sharp2448 The `date_range` feature relies on the data being sorted in ascending order when stored. Looking at the output (which is returned in the stored order), you seem to have the data in descending order, which triggers undefined behaviour.

We are working on #203 to make this case clear.

There are plans to support `date_range` on descending data that are written with the new flags written introduced above. We're also considering a sort feature.

---

@bulltools Could you confirm if you just want to use `date_range` or `date_range` plus a row limit?

**Comment by bulltools** [comment]
id like to use `date_range` to retrieve data between two dates, ensuring a minimum of `n` rows (so essentially a row minimum). If the result has fewer than `n` rows, i want to fetch enough additional rows so that `n` = minimum rows

**Comment by sharp2448** [comment]
@qc00 Ahhh that makes sense now. I have tried a lot but didn't think about that 😅.

Well thank you for the clarification!
Looking forward to trying new features as they come.
And appreciate making the C++ Arctic backend open source.🙏

My company extensively experimenting with the Arctic so we might become your customer at some point.

Keep up the great job!

**Comment by sharp2448** [comment]
Just came back to confirm it worked.
So `df.sort_index(ascending=True)` was the fix for me...

**Comment by qc00** [comment]
@bulltools I think your request is a separate one.

You effectively want to be able to supply a `date_range` to `head()`. This is not very difficult to code but may cause some confusion on semantics. I have raised #245
