### ISSUE TITLE
Run CI against multiple dependency versions

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#250]
## Libraries to cover:

- Pandas
- Numpy (contemporary with the Pandas version)

## Ways to implement this:

Option 1: We can use our newly purchased runners and spin up parallel test jobs for all supported dependency-python combinations. This may make the slowest job in the build worse.

Option 2: We pick the dependency versions that are contemporary with each Python version and only test that version + the latest.

**Comment by poodlewars** [comment]
I'm resolving this as we've already done it eg https://github.com/man-group/ArcticDB/blob/93906d925982699aab280f2b80b12ec658f0a38e/build_tooling/requirements-compatibility-py36.txt#L4
