### ISSUE TITLE
ArcticDB does not respect HTTP_PROXY and HTTPS_PROXY 

### ISSUE THREAD

**Issue by alokwatve** [man-group/ArcticDB#262]
These are standard options generally respected by other S3 clients like boto3. Without these, it will be difficult to access arcticdb from behind a corp firewalls.

**Comment by qc00** [comment]
Hi, we do [support](https://github.com/man-group/ArcticDB/blob/5b4835685c5d13d66d2b890ce952dc0b87994dae/cpp/arcticdb/storage/s3/s3_storage.hpp#L205) these and many users were able to use proxies.

Could you confirm `os.getenv()` returns the expected settings in Python?

**Comment by mehertz** [comment]
I'm going to close this ticket as we believe ArcticDB this functionality to be complete. Can re-open if you encounter the same issue again using the latest version of ArcticDB off of PyPi.
