### ISSUE TITLE
Support of big endian machines

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#263]
(This is not a commitment to support other architectures but to provide a place to collect what we may have to do to support one.)

- [ ] The writing code should detect the input byte order and handle it accordingly:
    - Do we store the input byte order + a mark in the metadata or always convert to little endian?
- [ ] The reading code should explicitly indicate the byte order of the returned frame where the return type allows
- [ ] `MsgPackNormalizer` [view](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.view.html)s the byte buffer as `uint64`. Its byte order handling should be consistent with the above.

**Comment by poodlewars** [comment]
I'm going to close this as we have no plans to work on this in the foreseeable future. Feel free to add comments with additions to the list, though.
