### ISSUE TITLE
ArcticDB should have a concept of users/owners

### ISSUE THREAD

**Issue by Chen-Oliver** [man-group/ArcticDB#280]
ArcticDB currently has no concept of "users”. Any symbol or library created in a bucket+prefix is considered to be owned by a single anonymous user. We would like the concept of users so that symbols and libraries can be listed according to the owner (user who created it).

**Comment by qc00** [comment]
We're very interested in learning the details of your use case. Could you clarify:

* Do you need any access permission/restriction to be assigned to each "user" (prefix)?
* If not, would "namespaces" be a more appropriate description of the feature you want?
* Do you want one user to be able to list a different user's libraries (e.g. by passing some parameter)?

**Comment by jamesmunro** [comment]
@Chen-Oliver A common pattern is to create libraries with a user prefix.

```python
arctic.create_library('username.mydata')
```

**Comment by jamesmunro** [comment]
Closing as stale.
