### ISSUE TITLE
Azure Storage

### ISSUE THREAD

**Issue by RockScience** [man-group/ArcticDB#284]
Hello,

Are you planning to release a version that can store the files on Azure instead of S3?

**Comment by mehertz** [comment]
Hiya. Yes! We absolutely do! 

I've created a new ticket that we'll use to track this work (#290).

I'm going to close this ticket now - please use that for tracking.

**Comment by mehertz** [comment]
Scratch that - reopening this ticket. Will use this ticket for tracking.

This will involve writing a [new storage backend](https://github.com/man-group/ArcticDB/blob/master/cpp/arcticdb/storage/storage.hpp#L82) that supports Azure Blob Storage.

The SDK includes a [emulator](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-emulator) that we can use for testing purposes.

**Comment by RockScience** [comment]
Thank you!
I understand it is not yet done at the moment
But do you expect possibility to move files from S3 to Azure and vice versa?
( cf #296 )

**Comment by phoebusm** [comment]
Tasks:
- [ ] Basic read/write operation implementation
- [ ] Python layer library adapter
- [ ] Test cases
- [ ] Add enumerator `Azurite` in Github action

Possible tasks:
- [ ] Proxy support

**Comment by mehertz** [comment]
- [ ] Document & getting started guide

**Comment by phoebusm** [comment]
Batch delete cannot be test in the pipeline due to a bug/missing feature in Azurite
https://github.com/Azure/Azurite/issues/1822

**Comment by phoebusm** [comment]
Linux users, who has the SSL certificate path incorrectly setup, will have exception with meaningless content. It is due to a bug in Azure C++ SDK: https://github.com/Azure/azure-sdk-for-cpp/issues/4738
Users are required to turn on Azure debug log to figure out what's the problem.
`export AZURE_LOG_LEVEL=1`
