### ISSUE TITLE
dedup library option seems to not work

### ISSUE THREAD

**Issue by Zatura** [man-group/ArcticDB#294]
I am doing several unit tests using overlapping dataframes with datetime64 indexes and dedup seems to have no difference, I checked arcticdb unit tests but I did not find any useful unit test that tells how it should behave.
Tested with 3 different library options using LMDB and writing using lib.write and even lib.append function,
I used ```watch -d ls -lh``` on the LMDB folder where data.mdb file is store to check for size changes, after several writes it seems that it always increase in size at the same rate no matter if dedup is True or false:
```python
connection.create_library(name="mylib")
connection.create_library(name="mylib", library_options=LibraryOptions(dedup=True))
connection.create_library(name="mylib", library_options=LibraryOptions(dedup=True, dynamic_schema=True))
```
I didn't understand clearly how dedup should behave, however, I tested 2 scenarios:
- Deduplication when the dataframe to be saved has duplicate values
- Deduplication when the LMDB has some duplicate data (overlapping) with the dataframe to be saved

None of those scenarios worked, if using lib.append, I receive the following exception as expected, since this behaviour is explained on docs
```
[arcticdb] [error] E_ASSERTION_FAILURE Can't append dataframe with start index 2021-12-19 00:00:00.0 to existing sequence ending at 2021-12-20 00:00:00.0
```

Example of unit test I did
```python
def test_deduplication_on_write(self):
    connection = Arctic(LOCAL_PATH)
    connection.create_library(name="mylib", library_options=LibraryOptions(dedup=True))
    lib = connection["mylib"]        
    dataframe_duplicates = dataframe_duplicate_fixture()
    date_range = (datetime(2021, 12, 25, 12, 0, 9), datetime(2021, 12, 25, 12, 0, 50))

    # lib.append or lib.write, it doesn't seems to be working.
    lib.write(symbol='DUPUSD', data=dataframe_duplicates)
    read_dataframe = lib.read(symbol='DUP-USD', date_range=date_range)

    self.assertEqual(len(read_dataframe), 1)
```
This is the fixture I am using
```python
def dataframe_duplicate_fixture():
    dataframe = pandas.DataFrame([
        {'date': datetime(2021, 12, 25, 12, 0, 10), 'price': 1111.0, 'quantity': 100.0, 'side': 'buy'},
        {'date': datetime(2021, 12, 25, 12, 0, 10), 'price': 1111.0, 'quantity': 100.0, 'side': 'buy'},
        {'date': datetime(2021, 12, 25, 12, 0, 10), 'price': 1111.0, 'quantity': 100.0, 'side': 'buy'},
        {'date': datetime(2021, 12, 25, 12, 0, 10), 'price': 1111.0, 'quantity': 100.0, 'side': 'buy'},
        {'date': datetime(2021, 12, 25, 12, 0, 10), 'price': 1111.0, 'quantity': 100.0, 'side': 'buy'},
        {'date': datetime(2021, 12, 25, 12, 0, 10), 'price': 1111.0, 'quantity': 100.0, 'side': 'buy'},
    ])
    dataframe.index = pandas.to_datetime(dataframe['date'], unit='s')
    dataframe.index.name = 'index'
    return dataframe.drop(columns='date')
```

**Comment by qc00** [comment]
The `dedup` option controls has some limitations explained in its [API docs](https://docs.arcticdb.io/api/arcticdb/arcticdb.LibraryOptions).

In your specific case, the entire data fits in one segment and dedup cannot reuse part of a segment, so a new one is always written out. You have to set the `rows_per_segment` option to a very small value to see a difference in your test.

In general, dedup is most useful for continuously appended datasets with a large number of rows.

**Comment by Zatura** [comment]
Thank you for your clarification, I am closing the issue.
