### ISSUE TITLE
add functionality to move library from one bucket to another

### ISSUE THREAD

**Issue by RockScience** [man-group/ArcticDB#296]
Hello,

There could be situations where people need to reoganize the storage (changing subscriptions, permissions...) 
Is there a way to move an entire library from one S3 bucket to another, while keeping all the data intact including version dates etc...?

**Comment by qc00** [comment]
Currently, the S3 URL is also stored alongside the library configuration, and we don't yet have a public API to update that, so even if you can move the objects, it won't be readable.

We will need to implement the [relative path](https://github.com/man-group/ArcticDB/issues/235#issuecomment-1516406145) change first.

**Comment by jamesmunro** [comment]
Hi @RockScience, I'm going to close this, as we would currently regard library moving tools as an enterprise feature.  Feel free to contact us if interested.  For open source users, you can use S3 tools to copy/backup whole buckets, or read and write the data-frames from one bucket to another in python.

**Comment by jamesmunro** [comment]
> Currently, the S3 URL is also stored alongside the library configuration, and we don't yet have a public API to update that, so even if you can move the objects, it won't be readable.
> 
> We will need to implement the [relative path](https://github.com/man-group/ArcticDB/issues/235#issuecomment-1516406145) change first.

This was fixed.
