### ISSUE TITLE
`robin-hood-hashing` deprecation 

### ISSUE THREAD

**Issue by jjerphan** [man-group/ArcticDB#327]
[`robin-hood-hashing`](https://github.com/martinus/robin-hood-hashing/) is used as a dependence.

Yet [it has been deprecated last year and is currently unmaintained except to fix critical bugs](https://github.com/martinus/robin-hood-hashing/commit/bdfe16d907a0b1f76fd8627a57584d4c3b67cea0).

The author points to [`ankerl::unordered_dense::{map, set}`](https://github.com/martinus/unordered_dense), a pair of alternatives he actively works on and maintains.

For now, finding a replacement for `robin-hood-hashing` might not be a priority, but it might be in the future.

**Comment by willdealtry** [comment]
Thanks for the heads-up. I'll be looking at the performance of some features that depend heavily on hashing at some point, so if this is faster the it would be a good replacement. For the time being I think robin_hood is widely used enough that the likelihood of critical bugs emerging at this stage is low.

**Comment by jjerphan** [comment]
[Recent benchmarks from the author](https://martin.ankerl.com/2022/08/27/hashmap-bench-01/) might help making informed decisions.
