### ISSUE TITLE
Python 3.6 end-of-life

### ISSUE THREAD

**Issue by jjerphan** [man-group/ArcticDB#332]
[Python 3.6 has known its end of life on 23rd December 2021 and is now unsupported](https://devguide.python.org/versions/#unsupported-versions).

Yet, ArcticDB still [tests against](https://github.com/man-group/ArcticDB/blob/master/.github/workflows/build.yml#L50) and [distributes wheels](https://pypi.org/project/arcticdb/#files) for this version.

Are there still use cases or constraints preventing dropping the support for Python 3.6?

**Comment by mehertz** [comment]
We still have active users of Python 3.6 I'm afraid. Might be possible to stop building for Python 3.6 in ~6 months time but certainly not before then.
