### ISSUE TITLE
Windows pip install

### ISSUE THREAD

**Issue by mr-easy** [man-group/ArcticDB#342]
>pip install arcticdb
ERROR: Could not find a version that satisfies the requirement arcticdb (from versions: none)
ERROR: No matching distribution found for arcticdb

>python --version
Python 3.10.0

Which version should I be using? Is it not available for windows?
How can we build it from source?

**Comment by TianQingX** [comment]
#295

They may publish this week. 
 https://github.com/man-group/ArcticDB/actions/runs/4830924624/jobs/8608012869

**Comment by poodlewars** [comment]
Closing as duplicate of #295

**Comment by qc00** [comment]
We're pleased to announce [v1.1.0](https://github.com/man-group/ArcticDB/releases/tag/v1.1.0) has been released to [Pypi](https://pypi.org/project/arcticdb/) with Windows builds.
