### ISSUE TITLE
LMDB, delete_library(), AttributeError: 'Library' object has no attribute 'version_store'

### ISSUE THREAD

**Issue by wheelfredie** [man-group/ArcticDB#345]
New user to ArcticDB here. Facing the issue of error for delete_library(“name”) for local LMDB
AttributeError: 'Library' object has no attribute 'version_store'

Storage type: local LMDB
OS: Ubuntu 22.04.2 LTS x86_64
arcticdb: 1.0.1
python: 3.10.6

I downloaded mongodb, created a database, and pipenv install arcticdb. Tested library by creating and deleting

Code:
```python
>>> from arcticdb import Arctic
>>> import pandas as pd 
>>> store = Arctic('lmdb://localhost:27017/historical_data')
>>> store.create_library("option.1day"]
>>> store.list_libraries()
['option.1day']
>>> store.delete_library('option.1day')
```

```python-traceback
AttributeError Traceback (most recent call last)
Cell In[5], line 1
----> 1 store.delete_library('option.1day')

File [~/.local/share/virtualenvs/arcticdb-WCXsRD7e/lib/python3.10/site-packages/arcticdb/arctic.py:175](https://file+.vscode-resource.vscode-cdn.net/home/w/scripts/arcticdb/~/.local/share/virtualenvs/arcticdb-WCXsRD7e/lib/python3.10/site-packages/arcticdb/arctic.py:175), in Arctic.delete_library(self, name)
173 if not self._library_manager.has_library(name):
174 return
--> 175 self._library_adapter.delete_library(self[name], self._library_manager.get_library_config(name))
176 self._library_manager.remove_library_config(name)

File [~/.local/share/virtualenvs/arcticdb-WCXsRD7e/lib/python3.10/site-packages/arcticdb/adapters/lmdb_library_adapter.py:68](https://file+.vscode-resource.vscode-cdn.net/home/w/scripts/arcticdb/~/.local/share/virtualenvs/arcticdb-WCXsRD7e/lib/python3.10/site-packages/arcticdb/adapters/lmdb_library_adapter.py:68), in LMDBLibraryAdapter.delete_library(self, library, library_config)
67 def delete_library(self, library: NativeVersionStore, library_config: LibraryConfig):
---> 68 return library.version_store.clear()

AttributeError: 'Library' object has no attribute 'version_store'
```
Also, when i create a collection in mongodb, i cannot see it in list_libraries in arcticdb (will be empty), and vice versa.

Is there currently no solution for this on LMDB?

I also tried to manually delete the lmdb file through terminal rm - rf, but the symbol remains and the files comes back on its own even when removing from trash also.
Thank you:)

**Comment by poodlewars** [comment]
Hi, I fixed the `delete_library` issue in https://github.com/man-group/ArcticDB/commit/6016157e3e499026f327a39fdf3ce6aa8df2533f so the fix will be in our next minor release (early this week).

Regarding the other questions I don't understand your setup where you have a mixture of LMDB and MongoDB at once. The LMDB storage should be backed by a file system, not by Mongo.

We do anticipate adding support for Mongo as a first class storage in due course.

**Comment by mehertz** [comment]
Hi - now 1.1 is released could you give it a try and confirmed that `delete_library` is resolved please.
