### ISSUE TITLE
RFC: Setup for running test suites in parallel

### ISSUE THREAD

**Issue by jjerphan** [man-group/ArcticDB#350]
Currently, Python tests suite can be run in parallel using [`build_tooling/parallel_test.sh`](https://github.com/man-group/ArcticDB/blob/c90ee1060f064cdd6ed09d6aa5ddd675cdfc49fe/build_tooling/parallel_test.sh).

This script setups workers, each of which sequentially runs a portion of the tests using `pytest`, and aggregates their results saved as test assets stored in folders.

This is the current setup used in the CI. Yet, reading this comment:

https://github.com/man-group/ArcticDB/blob/d67d3e59c2385a36e7775a232c768b538eb7aa1a/build_tooling/parallel_test.sh#L22-L24

were there problems running tests in parallel in the past? Is the current setup addressing specific needs?

Alternatively, [`pytest-xdist`](https://pytest-xdist.readthedocs.io/en/stable/index.html) might be a good and maintained solution to handle this complexity. It is an extension of `pytest` which exposes CLI parameters allowing running the test suite in parallel [across several CPUs](https://pytest-xdist.readthedocs.io/en/stable/distribution.html) and [in subprocesses if needed](https://pytest-xdist.readthedocs.io/en/stable/subprocess.html). It internally setups workers and aggregates their results while maintaining unchanged traces of run (parallel runs' outputs are identical to sequential runs').

What do you think?

**Comment by qc00** [comment]
I believe the "mystery lock" problem is current and probably relates to some files created in the working directory of the test runner.

The script also does other stuff:

* Build a directory that's just the test assets, so can't access other Python source not in the wheel
* `catchsegv`
* Make sure the test output goes to the outside of the CIBuildWheel Docker container even if the test fails
* Upcoming GitHub Actions annotation

**Comment by jjerphan** [comment]
Yes. [`pytest-split` also gives limitations of `pytest-xdist`](https://jerry-git.github.io/pytest-split/#motivation).

**Comment by poodlewars** [comment]
@G-D-Petrov is trying out some ideas like this. I'll close this ticket.
