### ISSUE TITLE
Errorcode and exception ecosystem improvement

### ISSUE THREAD

**Issue by phoebusm** [man-group/ArcticDB#353]
... Continuing #191 

- [x] Display error code in python error message
- [x] Ensure all not found errors have known error codes (for example - library/symbol not found)
- [x] Ensure that S3/network errors - being unable to write all have a defined error category
- [ ] Restructure inheritance hierarchy so that every exception can be captured specifically and by parent exceptions
- [ ] Fit existing ArcticNativeNotYetImplemented exceptions into the new exception ecosystem while maintaining backward compatibility 
- [ ] Update the docs

**Comment by poodlewars** [comment]
I'll resolve this one. I think it's covered by other open tickets.
