### ISSUE TITLE
`Arctic()` URI builder(s) or equivalent

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#363]
To allow the URI components to be collected in a piecemeal way.

For example, a wrapper for ArcticDB might have fixed values for some parts of the URI but allow other parts to be set by the user. Currently, such code must pass around the user-supplied parts until it's ready to format the final string. This is cumbersome and makes it difficult to support multiple storage types.

It could be simple `dataclass`es or extending an existing URI builder class.

We might want to have one type per storage type.

This will also allow us to provide APIs to parse/convert foreign URI formats (e.g. for S3).

**Comment by jamesmunro** [comment]
**Problem statements**

is there an elegant way to get the URI that was used to create an arctic instance.
Specifically, I'm looking at the parallel writes use case, below is from the user guide
```
import pyspark

# This example assumes the below variables (host, bucket, access, secret) are validly set
ac = Arctic(f"s3://{HOST}:{BUCKET}?access={ACCESS}&secret={SECRET})

def _load(work):
    # This method is run in parallel via Spark.
    host, bucket, access, secret, symbol, library, file_path = work
    ac = Arctic(f"s3://{host}:{bucket}?access={access}&secret={secret}")
```

Imagine this setup:
```class SomeDataProcessingClassUsingArctic:

    def __init__(self, ac):
        self.ac = ac

    def some_processing(self):
        tasks = slef.somehow_get_tasks()
        # kick off parallel processing
```

**Comment by willdealtry** [comment]
Can you add a bit more detail about what the API would be? I'm finding it hard to visualize what user interaction with this wrapper class would look like

**Comment by qc00** [comment]
A few examples:

### Collecting URI parts from different functions:

```python
s3_uri = ArcticS3URI(bucket="b")

if prod_environment:
   add_credentials_from_secrets_store(s3_uri)  # This can both read and write the argument for max flexibility
else:
   add_dev_credentials(s3_uri)

arctic = Arctic(s3_uri)
```

### Set storage-agnostic settings

```python

def createPerUserArctic(uri: Union[ArcticS3URI, ArcticAzureURI]):
   uri.path_prefix = get_current_user()
   return Arctic(uri)
```

### Parse foreign URI formats

```python
s3_uri = ArcticS3URI.parseS5cmd("s3s://...")
arctic = Arctic(s3_uri)
```

In general, it's much easier to deal with objects with discrete fields than trying to manipulate a custom URL format.

**Comment by jamesmunro** [comment]
Let's move to the standard URI scheme first.
