### ISSUE TITLE
Improve VersionMap thread-safety

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#368]
The per-`VersionMapEntry` lock is not widely used, so many operations like `storage_reload()` are not reliably protected.

In fact, the "lock table" should probably be replaced with:

* Atomic exchanges in `storage_reload()`
* Reloading the version chain each time a `VersionRef` is written
    * A local mutex can't protect against remote overwrites anyway
    * Any conflicting write in the same client should be checked and rejected much earlier in the call to avoid orphaned keys
    * If the reloaded chain shows that our version did not win, we should proceed to delete the keys to avoid orphaning them

**Comment by willdealtry** [comment]
I don't really want to introduce locking on version map entries, it has been considered before and rejected. VersionMapEntry objects as handed out should be logically const, so they don't need to be locked, and the only thing that should modify them is the VersionMap class. The error at the moment I suspect comes from the fact that the VersionMap doesn't reliably reload each entry only once to the earliest necessary point, which is addressed in this branch: https://github.com/man-group/ArcticDB/tree/generic_parallel_get_version

**Comment by qc00** [comment]
Result of a catch-up with @willdealtry:

* `storage_reload()` should not `get_entry()` at the start but should use a new method to replace the existing entry (atomically or with lock) at the end
* The `LockTable` is only used by certain async `Task`s and doesn't provide protection on other operations. It seems to be more of a symbol-level operation serialisation mechanism than a `VersionMapEntry` thread-safety device.
* `VersionMapEntry` should be returned as `const` as much as possible
* If we make `VersionMapEntry` immutable, any new `VersionMapEntry` (from a version write) should internally reuse keys from the previous `Entry`.
  Possible ways discussed:
    * Store all keys on a copy-on-write linked list, each node containing a `shared_ptr` to the next. This can get inefficient as the list grows.
    * Instead of each linked list node holding one key, we mirror the "compacted keys" concept in RAM. I.e. the tail node on the linked list points to a list of keys. Once the list grows to a certain number of nodes, we atomically compact.
    * The compaction can be done via `storage_reload()`.
      This is not as costly as it seems because when the list grows to that size, we want to check if the cache still matches the storage anyway.
* We will not release the GIL for write operations at the moment
