### ISSUE TITLE
Inaccurate/confusing error message when calling lib.update on previously-written unsorted data

### ISSUE THREAD

**Issue by Naich** [man-group/ArcticDB#369]
After upgrading to v1.1.0, lib.update() throwed UnsortedDataException: E_UNSORTED_DATA When calling update on sorted data, the input data must be sorted.

However the Dataframe I used was with sorted index:
```python
> print(df_ticker.index.is_monotonic_increasing)
True
> lib.update(symbol, df_ticker)
UnsortedDataException                     Traceback (most recent call last)
File ~/arctic/lib/python3.8/site-packages/arcticdb/version_store/library.py:723, in Library.update(self, symbol, data, metadata, upsert, date_range, prune_previous_versions)
    656 def update(
    657     self,
    658     symbol: str,
   (...)
    663     prune_previous_versions=False,
    664 ) -> VersionedItem:
    665     """
    666     Overwrites existing symbol data with the contents of ``data``. The entire range between the first and last index
    667     entry in ``data`` is replaced in its entirety with the contents of ``data``, adding additional index entries if
   (...)
    721     2018-01-04       4
    722     """
--> 723     return self._nvs.update(
    724         symbol=symbol,
    725         data=data,
    726         metadata=metadata,
    727         upsert=upsert,
    728         date_range=date_range,
    729         prune_previous_version=prune_previous_versions,
...
   (...)
    798         host=self.env,
    799     )
UnsortedDataException: E_UNSORTED_DATA When calling update on sorted data, the input data must be sorted.
```
also tried  `lib.update(symbol, df_ticker.sort_index())`, same error.

here is the symbol data stored in db:
`lib.read(symbol).data`
| index | Time                   | Time_int   | Volume| Price| Direction |
|-------------------------|------------------------|-------------|------------|----------|------------|
| 2021-01-04 10:17:41.940 | 2021-01-04 10:17:41.940 | 101741940   | 8,967,603 | 18.59    | 2          |
| 2021-01-04 10:17:42.190 | 2021-01-04 10:17:42.190 | 101742190   | 8,967,934 | 19.35    | 3          |
| 2021-01-04 10:17:42.210 | 2021-01-04 10:17:42.210 | 101742210   | 8,967,950 | 18.00    | 2          |
| 2021-01-04 10:17:42.250 | 2021-01-04 10:17:42.250 | 101742250   | 8,968,002 | 18.60    | 2          |
| 2021-01-04 10:17:42.290 | 2021-01-04 10:17:42.290 | 101742290   | 8,968,053 | 18.60    | 2          |
| ...                     | ...                    | ...         | ...        | ...      | ...        |
| 2023-05-08 14:59:59.780 | 2023-05-08 14:59:59.780 | 145959780   | 33,246,442| 13.26    | 3          |
| 2023-05-08 14:59:59.830 | 2023-05-08 14:59:59.830 | 145959830   | 33,246,839| 13.32    | 3          |
| 2023-05-08 14:59:59.900 | 2023-05-08 14:59:59.900 | 145959900   | 33,247,074| 13.31    | 3          |
| 2023-05-08 14:59:59.930 | 2023-05-08 14:59:59.930 | 145959930   | 33,247,217| 13.26    | 3          |
| 2023-05-08 14:59:59.940 | 2023-05-08 14:59:59.940 | 145959940   | 33,247,287| 13.32    | 3          |

here is the df_ticker I tested, only 3 lines:
| index | Time                   | Time_int| Volume| Price| Direction |
| ----------------------| ----------------------| ----------|-------|--------|-----------|
| 2023-05-11 09:15:00.000| 2023-05-11 09:15:00.000| 91500000  | 18    | 11.56  | 2         |
| 2023-05-11 09:15:00.130| 2023-05-11 09:15:00.130| 91500130  | 21280 | 13.56  | 3         |
| 2023-05-11 09:17:14.550| 2023-05-11 09:17:14.550| 91714550  | 212376| 11.57  | 6         |

**Comment by mehertz** [comment]
That's very strange - it must think that `df_ticker.sort_index()` is still unsorted. It tests this simply by computing `df.index.is_monotonic_increasing` - mind double checking that that returns `True` for your DF?

**Comment by mehertz** [comment]
Also, did you write the data prior to 1.1.0?

**Comment by Naich** [comment]
> Also, did you write the data prior to 1.1.0?

Thanks for your quick response!
Yes, previous data was written with ArcticDB v1.0.1, and updating in that version worked.
With your hint, I found the old data in db seemed not monotonic.
```python
>>> old_data = lib.read(symbol).data
>>> old_data.index.is_monotonic_increasing
False
```
So this is caused by old data not sorted, sort and rewrite solved the issue.
```python
old_data = lib.read(symbol).data
old_data_sorted = old_data.sort_index()
lib.write(symbol, old_data_sorted)

lib.update(symbol, df_ticker, upsert=True) #success
```

**Comment by jamesmunro** [comment]
This was fixed by this change: 
https://github.com/man-group/ArcticDB/commit/686c54a2ab8f9586e74ab0eca125ad7966789e16
