### ISSUE TITLE
Add more support info to exception messages

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#372]
# Python
In addition to the error code, we should ensure each exception `__str__` includes the version and platform. Otherwise, we'll have to ask the user each time which adds friction.

We should code this in an extensible/open-ended way, so other contextual info (e.g. storage type) can be added in the future.

# C++
# *nix
We should consider loading `libSegFault.so` automatically

# Windows
Consider implementing [Structured exception handling](https://learn.microsoft.com/en-us/cpp/cpp/structured-exception-handling-c-cpp?view=msvc-170)

# Documentation
Provide/link to clear instructions on how to collect core dumps

**Comment by poodlewars** [comment]
I think asking users to provide this info is reasonable
