### ISSUE TITLE
Improve error message when it is out-of-memory

### ISSUE THREAD

**Issue by phoebusm** [man-group/ArcticDB#374]
Currently if it is out-of-memory, no proper error message will be displayed.
e.g. `arcticcxx.exceptions.ArcticNativeCxxException: std::invalid_argument(Cursor overflow in chunked_buffer ptr_cast, cannot read 8 bytes from a buffer of size 0 with cursor at 0, as it would required 8 bytes. )`
or simply
`$ python debug.py 
Killed`

**Comment by willdealtry** [comment]
This message is not connected to running out of RAM

**Comment by mehertz** [comment]
This isn't an out-of-memory issue. Without a repro in this case I don't think we'll be able to address so closing.
