### ISSUE TITLE
ArcticDB throws when timezone is not  a string

### ISSUE THREAD

**Issue by willdealtry** [man-group/ArcticDB#378]
`TypeError                                 Traceback (most recent call last)
index_names, index_norm, dynamic_strings, string_max_len)
    310         if index_tz is not None:
--> 311             index_norm.tz = index_tz
    312 

TypeError: bad argument type for built-in operation`

This is due to index_tz not being a string, protobuf throws when it is assigned to   index_norm.tz

**Comment by qc00** [comment]
I think your second attempt might be the same problem. The differences in error messages might be due to different protobuf versions.
