### ISSUE TITLE
Editing the top level CMakeLists.txt triggers a full rebuild

### ISSUE THREAD

**Issue by vasil-pashov** [man-group/ArcticDB#402]
**Is your feature request related to a problem? Please describe.**
When CMake is reconfigured, which happens if the top level CMakeLists.txt gets edited or when reconfiguring is done manually (e.g. via clicking the reconfigure button in the IDE) a full rebuild of the whole project is triggered. The rebuild is triggered even if no cpp/hpp/h files were changed.

**Describe the solution you'd like**
Fix the build process so that editing the CMakeLists.txt does not require full rebuild. If new files are added to the project they must, obviously, be compiled. But if the changes are only CMake related we must not rebuild the whole project (e.g. adding a custom target should not rebuild the project).

**Describe alternatives you've considered**
No alternatives.

**Additional context**

**Comment by poodlewars** [comment]
Is this not always the case with CMake?

Even so, if it is, we should set up SCCACHE for our dev environments which would still fix most of the pain. It's already used in the CI build and should be really easy.

**Comment by vasil-pashov** [comment]
> Is this not always the case with CMake?
> 
> Even so, if it is, we should set up SCCACHE for our dev environments which would still fix most of the pain. It's already used in the CI build and should be really easy.

No, reconfiguring CMake should (almost) never trigger any kind of (even) partial builds.
