### ISSUE TITLE
unable to connect to my bucket

### ISSUE THREAD

**Issue by markeasec** [man-group/ArcticDB#410]
### Describe the bug

Hi,
I am trying to migrate from Arctic to ArcticDB.
I created a bucket in s3, called chum_bucket.

I can't create any libraries in this bucket, when I do, I get:

[2023-05-19 11:59:06.958] [arcticdb] [error] Got unexpected error: '99' : curlCode: 6, Couldn't resolve host name

I am doing this from an Amazon Linux box inside US-East-1, running python3.7

### Steps/Code to Reproduce

```
from arcticDB import Arctic
x = Arctic('s3://s3-us-east-1.amazonaws.com:chum_bucket?aws_auth=true')
x.create_library('AAPL')
```

### Expected Results

should be able to create a library called AAPL.

### Actual Results

```
[2023-05-19 11:59:06.958] [arcticdb] [error] Got unexpected error: '99' : curlCode: 6, Couldn't resolve host name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.local/lib/python3.7/site-packages/arcticdb/arctic.py", line 151, in create_library
    if self._library_manager.has_library(name):
RuntimeError: std::exception
```

### OS (Including Linux Distribution)

Amazon Linux AMI 2

### Python Version

3.7

### ArcticDB Version

1.0.1

### Backend storage used

AWS S3

### Additional Context

I'm able to access other AWS buckets and services from my box so the box is definitely authorized correctly. Specifically, I copied chum_bucket's permissions from another AWS bucket which I have no problem accessing on this box.

**Comment by qc00** [comment]
`Couldn't resolve host name` is very surprising. I don't think AWS SDK reported the actual problem.

It seems to be related to this: https://github.com/aws/aws-sdk-cpp/issues/1920

Also, could you verify the same issue occurs with ArcticDB version 1.1?

**Comment by qc00** [comment]
Does it work if you add `&region=us-east-1` to the end of the URI? I think the AWS SDK is very peculiar about this.

**Comment by markeasec** [comment]
unfortunately not, also even with the other URI format (below), which has the region, I still get the same error.
a = Arctic(s3://s3-us-east-1.amazonaws.com:chum_bucket?region=us-east-1&access=ACCESS&secret=SECRET)

**Comment by markeasec** [comment]
@qc00 : would you consider creating a dummy test bucket and share a URI to connect to it? That way we could isolate whether the issue is in the bucket config or somewhere else.

**Comment by markeasec** [comment]
Just following up to see if anyone could create a test bucket or if there is any other recommendations or suggestions for this issue.

**Comment by poodlewars** [comment]
Could it simply be an issue with your URI?

It is:
```
x = Arctic('s3://s3-us-east-1.amazonaws.com:chum_bucket?aws_auth=true')
```

but I think it should be

```
x = Arctic('s3://s3.us-east-1.amazonaws.com:chum_bucket?aws_auth=true')
```

**Comment by markeasec** [comment]
hmmm ok. that resolved the connectivity issue but I now get this error. 

[2023-06-02 13:20:32.666] [arcticdb] [warning] Failed to find segment for key 'C:my_lib' : No response body.
Traceback (most recent call last):
  File "migrate_arctic.py", line 20, in <module>
    lib = as3['my_lib']
  File "/home/ec2-user/.local/lib/python3.7/site-packages/arcticdb/arctic.py", line 96, in __getitem__
    self._library_manager.get_library(name),
arcticdb_ext.exceptions.StorageException: Composite: C:my_lib, 

regarding the URI, I would just suggest putting a more detailed URI example in the documentation. I don't think having a unique syntax is such a big issue but it would be good to make that explicit.
