### ISSUE TITLE
Got "Invalid lmdb error code -30792" when using append()

### ISSUE THREAD

**Issue by s-t-li** [man-group/ArcticDB#413]
### Describe the bug

Hi,
I got an error when using Library.append() to append a pandas.DataFrame to existed data.
1. read 2 csv as pd.DataFrame df1 and df2
2. write df1 to arcticdb store
3. append df2 to existed df1 stored in arcticdb
4. and then get error msg

the two csv as input:
df1: https://data.binance.vision/data/spot/monthly/klines/BTCUSDT/1s/BTCUSDT-1s-2023-01.zip
df2: https://data.binance.vision/data/spot/monthly/klines/BTCUSDT/1s/BTCUSDT-1s-2023-02.zip

### Steps/Code to Reproduce

```python
from arcticdb import Arctic
import pandas as pd


csv_col = [
    "datetime",
    "open",
    "high",
    "low",
    "close",
    "volume",
    "close_time",
    "turnover",
    "trades",
    "taker_buy_base_asset_volume",
    "taker_buy_quote_asset_volume",
    "ignore",
]

data_fields = [
    "open",
    "high",
    "low",
    "close",
    "turnover",
    "volume",
    "trades",
    "open_interest",
]

df1 = pd.read_csv("BTCUSDT-1s-2023-01.csv", names=csv_col)
df1 = df1.set_index("datetime")
df1.index = pd.to_datetime(df1.index * 1000000 + 1000000000)
df1 = df1.reindex(columns=data_fields).fillna(0)

df2 = pd.read_csv("BTCUSDT-1s-2023-02.csv", names=csv_col)
df2 = df2.set_index("datetime")
df2.index = pd.to_datetime(df2.index * 1000000 + 1000000000)
df2 = df2.reindex(columns=data_fields).fillna(0)

db = Arctic("lmdb://./database/arcticdb/bar")
db.create_library("exchange")
lib = db.get_library("exchange")
sym = "btcusdt_m"
lib.append(sym, df1)
lib.append(sym, df2)
```

### Expected Results

VersionedItem(symbol='btcusdt_m', library='exchange', data=n/a, version=30, metadata=None, host='LMDB(path=[e:\\quant\\alpha\\database\\arcticdb\\bar](file:///E://quant//alpha//database//arcticdb//bar))')

### Actual Results

---------------------------------------------------------------------------
InternalException                         Traceback (most recent call last)
Cell In[3], line 47
     45 sym = "btcusdt_m"
     46 lib.append(sym, df1)
---> 47 lib.append(sym, df2)

File [c:\ProgramData\anaconda3\lib\site-packages\arcticdb\version_store\library.py:648](file:///C:/ProgramData/anaconda3/lib/site-packages/arcticdb/version_store/library.py:648), in Library.append(self, symbol, data, metadata, prune_previous_versions, validate_index)
    572 def append(
    573     self,
    574     symbol: str,
   (...)
    578     validate_index: bool = True,
    579 ) -> Optional[VersionedItem]:
    580     """
    581     Appends the given data to the existing, stored data. Append always appends along the index. A new version will
    582     be created to reference the newly-appended data. Append only accepts data for which the index of the first 
   (...)
    646     2018-01-06       6
    647     """
--> 648     return self._nvs.append(
    649         symbol=symbol,
    650         dataframe=data,
    651         metadata=metadata,
    652         prune_previous_version=prune_previous_versions,
    653         validate_index=validate_index,
    654     )

File [c:\ProgramData\anaconda3\lib\site-packages\arcticdb\version_store\_store.py:690](file:///C:/ProgramData/anaconda3/lib/site-packages/arcticdb/version_store/_store.py:690), in NativeVersionStore.append(self, symbol, dataframe, metadata, incomplete, prune_previous_version, validate_index, **kwargs)
    688     self.version_store.append_incomplete(symbol, item, norm_meta, udm)
    689 else:
--> 690     vit = self.version_store.append(
    691         symbol, item, norm_meta, udm, write_if_missing, prune_previous_version, validate_index
    692     )
    693     return VersionedItem(
    694         symbol=vit.symbol,
    695         library=self._library.library_path,
   (...)
    699         host=self.env,
    700     )

InternalException: (Invalid lmdb error code -30792 while putting key d:btcusdt_m:1:0xcdae5a03055867cd@1684684221360907000[1675409601000000000,1675509600000000001])

### OS (Including Linux Distribution)

Windows 10 Professional 22H2 19045.2965

### Python Version

3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]

### ArcticDB Version

v 1.1.0

### Backend storage used

LMDB

### Additional Context

none.

**Comment by qc00** [comment]
This is a manifestation of issue #229. We are considering solutions.

In the meantime, you might want to use a local S3 server.
