### ISSUE TITLE
When concatenating arguments passed in the QueryBuilder, use `numpy.can_cast` to test whether the concat will be safe

### ISSUE THREAD

**Issue by GemDot-neubla** [man-group/ArcticDB#414]
**Is your feature request related to a problem? Please describe.**

We currently use the numpy concatenate function as a way of casting/promoting types from different lists to a common denominator:

```
    if len(collection) > 0:
        for value in collection:
            if value not in value_set:
                value_set.add(value)
                if isinstance(value, supported_time_types):
                    value = int(value.timestamp() * 1_000_000_000)
                elem = np.array([value]) if isinstance(value, (int, np.integer)) else np.full(1, value, dtype=None)
                array_list.append(elem)
                contains_integer = contains_integer or isinstance(value, (int, np.integer))
        value_list = np.concatenate(array_list)
        if contains_integer and value_list.dtype == np.float64:
            raise UserInputException("Invalid datatype conversion to double")
```

**Describe the solution you'd like**

Using cast seems to be a neater way to do it.
https://numpy.org/neps/nep-0042-new-dtypes.html#casting

The idea would be to use the np.promote_types function to work out the common type across all the arrays. Then we could promote all the types of those arrays to this common type, by using astype dumpy function.

**Describe alternatives you've considered**
The alternative is what is currently implemented, but it does not seem very plausible

**Additional context**

The concern was raised when working in a related but different problem

https://github.com/man-group/ArcticDB/pull/394#discussion_r1196768590

**Comment by qc00** [comment]
@willdealtry Please see the link at the bottom. It's related to converting `QueryBuilder` arguments, which is not performance sensitive (and already quite inefficient).

**Comment by mehertz** [comment]
Looks plausible:

```
In [9]: np.can_cast('uint', 'int', casting='safe')
Out[9]: False

In [10]: np.can_cast('int16', 'int32', casting='safe')
Out[10]: True
```

Seems like a better test?

**Comment by willdealtry** [comment]
Do we have any evidence that this is a performance problem at the moment?

**Comment by qc00** [comment]
To clarify, this suggestion is not motivated by performance at all. It's about using a numpy built-in feature to do the argument casting check where possible.

**Comment by willdealtry** [comment]
It's not clear from this issue why the proposed solution is better than the existing one. Is there a problem that is caused by the existing implementation?

**Comment by willdealtry** [comment]
My concern is that by out-sourcing the common type deduction we are introducing a dependency on external code that might differ between versions, and might change at some unspecified point in the future. If we're improving performance or fixing a bug, then perhaps the change is justified, but that would need to be made clear on the issue.
