### ISSUE TITLE
Add Azurite container to Github Action

### ISSUE THREAD

**Issue by phoebusm** [man-group/ArcticDB#428]
It is for test cases in https://github.com/man-group/ArcticDB/issues/284

**Comment by qc00** [comment]
Fetching Docker containers on GitHub Actions is very slow and blocking, so please avoid where possible.

The [official instructions](https://github.com/Azure/Azurite#github) suggests using `npm` to install?

**Comment by phoebusm** [comment]
Oh that is a very bad news....
I haven't used `npm` before. So the last thing I want to do right now is to be the pioneer, fidgeting `npm` on Github Action...

**Comment by qc00** [comment]
In that case, continue doing what you have now. We can optimise later.
