### ISSUE TITLE
Conda package fails to install in python 3.9 BQuant environment

### ISSUE THREAD

**Issue by reggied** [man-group/ArcticDB#434]
### Describe the bug

When attempting to install arcticdb in a standard Bquant python 3.9 conda environment, the environment can't be solved.

### Steps/Code to Reproduce

In a BQuant environment:

`mamba install arcticdb`

### Expected Results

The arcticdb conda package would be added to the Bquant conda environment.

### Actual Results

 Running /opt/bqplatform/bin/mamba install arcticdb --yes --quiet
Could not solve for environment specs
Encountered problems while solving:
  - package libthrift-0.18.0-h5e4af38_0 requires libevent >=2.1.10,<2.1.11.0a0, but none of the providers can be installed

The environment can't be solved, aborting the operation

### OS (Including Linux Distribution)

Linux jupyter-1f0c5f016470b75568oj2d1k68sjg-pod 5.10.178-162.673.amzn2.x86_64 #1 SMP Mon Apr 24 23:34:06 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Python Version

3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:22:55) 
[GCC 10.3.0]

### ArcticDB Version

Any available on conda-forge.

### Backend storage used

AWS

### Additional Context

This is our first attempt to install an arcticdb conda package.

**Comment by jjerphan** [comment]
Hi @reggied, thank you for reporting this problem.

Can you report your environment full specification using:

```bash
 /opt/bqplatform/bin/mamba list
```

**Comment by jjerphan** [comment]
https://github.com/conda-forge/arcticdb-feedstock/pull/5 rebuilt ArcticDB against `libevent >=2.1.10` and distributed it on conda-forge, making its resolution and usage now possible within BQuant as confirmed in direct discussions with @reggied.
