### ISSUE TITLE
Split `reload_symbol_list` into explicit wipe/rebuild methods

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#446]
Currently, the `reload_symbol_list` function has a data corruption [risk](https://github.com/man-group/ArcticDB/pull/393#discussion_r1200728143) if interrupted (as explained in its documentation).

There's a very simple fix: we should delete the compacted key(s) (`__symbols__`) first, forcing the symbol list cache to fall back to the version map.

This way it wouldn't matter if the `__add__` and `__del__ ` are left behind by an interrupted `reload_symbol_list` call.

**Comment by mehertz** [comment]
What if there are multiple compacted key(s)?

**Comment by qc00** [comment]
> What if there are multiple compacted key(s)?

They will all need to be deleted first.

**Comment by qc00** [comment]
We should also consider replacing `reload_symbol_list` with just a delete-only method (e.g. `flush_symbol_list_cache`).

See: https://github.com/man-group/ArcticDB/pull/393#discussion_r1200670846

**Comment by mehertz** [comment]
I think we should do the following:

1. Remove `reload_symbol_list`.
2. Add a new method: `wipe_symbol_list_cache`. See below for method docstring.
3. Add a new method: `compact_list_symbol_cache`. This method errors if it cannot compact the symbol list. 

`wipe_symbol_list_cache` docstring:

```
This method deletes the cache that is used to speed up calls to `list_symbols`. **Please do not call this method unless you are sure this is what you want to do!**

Note:

  * Whilst this call is executing, it must be allowed to run to successful completion before `list_symbols` is next called. Otherwise the cache risks being left in an inconsistent state resulting in out-of-date data being returned from calling `list_symbols`.
  * After running this method, `list_symbols` may take a long time to complete as the cache will have been removed. After `list_symbols` has run though it will have re-built the cache and successive calls will be faster.
```

**Comment by mehertz** [comment]
As a result of the above I am renaming this ticket from: `reload_symbol_list() must be allowed to run to completion or the symbol list will be inconsistent`

to: `Split reload_symbol_list into explicit wipe/rebuild methods`.

**Comment by qc00** [comment]
> 3. Add a new method: compact_list_symbol_cache. This method errors if it cannot compact the symbol list.

This seems unnecessary given calling `list_symbol()` after the "wipe" will do the same thing?
