### ISSUE TITLE
Can't install conda packages for MacOS

### ISSUE THREAD

**Issue by Harry040** [man-group/ArcticDB#450]
### Describe the bug

run  `mamba install -c conda-forge arcticdb` , Got these result.

<img width="641" alt="image" src="https://github.com/man-group/ArcticDB/assets/12960656/d75ba3f0-6566-47cb-bfd1-39a3e3298062">

### Steps/Code to Reproduce

`mamba install -c conda-forge arcticdb`

### Expected Results

None

### OS, Python Version and ArcticDB Version

<img width="722" alt="image" src="https://github.com/man-group/ArcticDB/assets/12960656/d11628a6-8e65-4089-b5d5-b74aa952772f">

**Comment by DerThorsten** [comment]
The packages for `osx-arm64` are not yet built on `conda-forge` but we are working on it.
