### ISSUE TITLE
ArcticDB coerces complex column names into strings

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#454]
### Describe the bug

ArcticDB stores all column names as strings, even Python tuples. This is unexpected.

### Steps/Code to Reproduce

```
In [33]: df.columns = df.columns.to_flat_index()

In [34]: df
Out[34]: 
     (1, 3)  (2, 4)
1 3       5       6
2 4       7       8

In [35]: lib.write('mi', df)
Out[35]: VersionedItem(symbol='mi', library='mi', data=n/a, version=1, metadata=None, host='LMDB(path=...)')

In [36]: lib.read('mi2').data
Out[36]: 
     (1, 3)  (2, 4)
1 3       5       6
2 4       7       8

In [37]: lib.read('mi2').data.columns
Out[37]: Index(['(1, 3)', '(2, 4)'], dtype='object')

In [38]: lib.read('mi2').data.columns[0]
Out[38]: '(1, 3)'

In [39]: type(lib.read('mi2').data.columns[0])
Out[39]: str

In [40]: type(df.columns[0])
Out[40]: tuple
```

### Expected Results

Either:

* An error to be thrown
* Full support for the type.

Practically speaking, we cannot support all custom Python types, however we should probably support Python tuples (useful for "faking" multi-index) and integer column names. Otherwise, we should raise an exception. 

### OS, Python Version and ArcticDB Version

All Python/OS versions are affected.

**Comment by willdealtry** [comment]
I don't think we should support Python tuples, it's a slippery slope to all kinds of problems. Column names are strings or integers, otherwise we should throw.

**Comment by willdealtry** [comment]
Bear in mind that in the case of dynamic schema, all we have to track the identity of columns is the name, since both the type and the position in the dataframe are allowed to change. For this same reason we don't support duplicate column names, even though Pandas allows them - because we need to be concerned with the evolution of the schema over time in a way that Pandas doesn't.

**Comment by alexowens90** [comment]
#1170 raises if anything but string or int column names are provided. Supporting further types as column names is a feature request, not a bug
