### ISSUE TITLE
Optimise `batch_write` by providing per-symbol parallelism

### ISSUE THREAD

**Issue by GemDot** [man-group/ArcticDB#455]
**Is your feature request related to a problem? Please describe.**
Currently, write batch operations are only parallelised at slice level. One of the potential benefits that the batch operations give to us is being able to parallelize them at symbol level as well. It benefits most when we have symbols that are not big enough to profit from the per slice parallelization. This task consists of adding the necessary changes to materialise this new parallelisation.

**Describe the solution you'd like**
First we need to be sure that all the functions involved in the write batch operations flow are returning back a future and not the actual data. If any of them is returning actual data, the chain of futures will be broken and the parallelism per symbol will not take effect. The way we convert actual data to a future is by using the Promise-Future folly mechanism, which is wrapped in ArcticDB via `submit_io_task`/`submit_cpu_task` operations. Also, we need to be sure that there are not intermediate `get` calls over these futures. Finally, we will obtain a vector of futures, where each of them correspond to an independent write operation. We finally use the `collect` folly method to converge these future into a single one, acting as a barrier.

**Describe alternatives you've considered**
Usage of std threads for each of the symbol writes of the batch operation. however, this is far more inefficient.

**Additional context**
It is important to emphasise that we already apply per-slice parallelisation in ArcticDB. It means that there will not be a significant performance difference by using these changes over write batch operations that are storing a large amount of data per symbol (those independent writes that span over more slices than number of cpu threads). Instead, write batch operations where the number of independent writes is large and the data to store is relatively small, could significantly benefit of it.

**Comment by qc00** [comment]
> First we need to be sure that all the functions involved in the write batch operations flow are returning back a future and not the actual data.

Is this duplicated from the `read_*` tasks? Sees less relevant to writing.

In general, writing is dominated by uploading data keys and pruning. The optimisation focus should be quite different from `read_*`
