### ISSUE TITLE
Apple Silicon build for conda-forge

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#458]

**Comment by DerThorsten** [comment]
* ArcticDb already builds fine with apple silicon. The is just a lack of a conda-forge build
* All packages are already migrated
* we are doing the apple-silicon build here https://github.com/conda-forge/arcticdb-feedstock/pull/6
* this is a bit more complicated than the normal builds as we need to cross-compile arm64 builds on an x64 machine.
* We cannot test the apple-silicon build in the github-actions (without using complicated emulation / cross-compilation) as there are no apple-silicon runners

**Comment by WeiLi1201** [comment]
Hi, I installed with command  `conda install -c conda-forge arcticdb` success, but still wrong when run examples.
I create a new conda env retest,  hope your update, thx. 
env :  m1  macOS 13.1
```
Traceback (most recent call last):
  File "/Users/****/pycharmProject/vnpy****/examples/alpha_platform/factor_research/arcticdb_learn.py", line 5, in <module>
    from arcticdb import Arctic, QueryBuilder
  File "/Users/****/anaconda3/envs/vnpy/lib/python3.9/site-packages/arcticdb/__init__.py", line 1, in <module>
    import arcticdb_ext as _ext
ImportError: dlopen(/Users/****/anaconda3/envs/vnpy/lib/python3.9/site-packages/arcticdb_ext.cpython-39-darwin.so, 0x0002): tried: '/Users/****/anaconda3/envs/vnpy/lib/python3.9/site-packages/arcticdb_ext.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/****/anaconda3/envs/vnpy/lib/python3.9/site-packages/arcticdb_ext.cpython-39-darwin.so' (no such file), '/Users/****/anaconda3/envs/vnpy/lib/python3.9/site-packages/arcticdb_ext.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by DerThorsten** [comment]
I can reproduce this and will investigate, thanks for reporting!

**Comment by chen-001** [comment]
Hi, I have macos 13.4.1 with M1 max. I have the same question to [WeiLi1201's issue](https://github.com/man-group/ArcticDB/issues/458#issuecomment-1632456545). I also get
 ```
dlopen(/Users/****/anaconda3/envs/vnpy/lib/python3.9/site-packages/arcticdb_ext.cpython-39-darwin.so, 0x0002): tried: '/Users/****/anaconda3/envs/vnpy/lib/python3.9/site-packages/arcticdb_ext.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/****/anaconda3/envs/vnpy/lib/python3.9/site-packages/arcticdb_ext.cpython-39-darwin.so' (no such file), '/Users/****/anaconda3/envs/vnpy/lib/python3.9/site-packages/arcticdb_ext.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

**Comment by jjerphan** [comment]
This must have been fixed by new builds being published on conda-forge thanks to https://github.com/conda-forge/arcticdb-feedstock/pull/39.

Feel free to comment or to re-open this PR if problems are still present.
