### ISSUE TITLE
Composite::empty() not equivalent to Composite::size() == 0

### ISSUE THREAD

**Issue by alexowens90** [man-group/ArcticDB#468]
`Composite<T>::empty()` does not correctly handle the case where (possibly recursively) the `values_` vector contains another Composite<T> which is empty.
i.e. if the `values_` vector of the root of the composite contains a single unique pointer to another `Composite<T>`, and the child's `values_` vector is empty, then `empty()` will return `false`, but `size()` will return 0.

**Comment by mehertz** [comment]
Appreciate this is about to be fixed, but is there a way for an end user to trigger this issue at present or is this entirely an internal issue?
