### ISSUE TITLE
Performance regression testing

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#481]
**Is your feature request related to a problem? Please describe.**
ArcticDB recently saw a performance regression. `batch_read` was mistakenly serialised without changing the functionality. As a result, no tests broke.

We should take steps to avoid accidentally creating performance regressions. 

**Describe the solution you'd like**
Ideally, I would like to use [airspeed velocity](https://asv.readthedocs.io/en/stable/) to identify the commits that have resulted in a performance regression. This could be run by CI off of commits to master.

Alternatively we could simply have a suite of tests with expected runtimes that could be run manually.

**Comment by poodlewars** [comment]
Should also consider read-/write-/storage- amplifications?

**Comment by poodlewars** [comment]
It would be good to make sure we have coverage for:

- Append
-  Update
-  Delete
-  Batch methods
-  Staged data
-  Compaction defragment_symbol_data and is_symbol_fragmented
-  Symbol list and symbol list compaction

all with realistically large data. Re-using (maybe re-parameterizing) existing tests seems like a good way to do this where possible, and we can write bespoke new tests where it isn't.

We should make sure we cover dynamic schema, sparse data and query builder queries as well.

Some of this relates to the real storage testing in #744 too, I imagine the performance benchmarking and the real storage testing will end up covering a similar set of features.

https://github.com/man-group/ArcticDB/blob/master/docs/mkdocs/docs/technical/contributing.md#development-guidelines
