### ISSUE TITLE
Local storage for 2 computers in a network

### ISSUE THREAD

**Issue by ivanli256138498** [man-group/ArcticDB#488]
### Describe the bug

Hi guys, I've got 2 computers to work with ArcticDB, when I create ArcticDB folder with ```'lmdb://Z:/arcticdb_lmdb_testing'``` (where Z drive is shared) on one computer. I cannot connect to ArcticDB using another computer, showing this error:

```
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-12-f2e3850a2ee7>", line 1, in <module>
    self.ac = Arctic(self._STORAGE_PATH)  # instantiate ArcticDB
  File "C:\Anaconda3\lib\site-packages\arcticdb\arctic.py", line 92, in __init__
    self._library_manager = LibraryManager(self._library_adapter.config_library)
  File "C:\Anaconda3\lib\site-packages\arcticdb\adapters\lmdb_library_adapter.py", line 51, in config_library
    lib = NativeVersionStore.create_store_from_config(env_cfg, _DEFAULT_ENV, self.CONFIG_LIBRARY_NAME)._library
  File "C:\Anaconda3\lib\site-packages\arcticdb\version_store\_store.py", line 270, in create_store_from_config
    lib = cls.create_lib_from_lib_config(lib_cfg, env, open_mode)
  File "C:\Anaconda3\lib\site-packages\arcticdb\version_store\_store.py", line 278, in create_lib_from_lib_config
    return lib_idx.get_library(lib_cfg.lib_desc.name, _OpenMode(open_mode))
arcticdb_ext.exceptions.InternalException: (mdb_env_open: No such file or directory)
```

Is it possible to resolve it? Thanks so much!

### Steps/Code to Reproduce

```ac = Arctic(r'lmdb://Z:/arcticdb_lmdb_testing')```

Testing on 2 computer within 1 local network

### Expected Results

Connect successfully without error

### OS, Python Version and ArcticDB Version

Python: 3.7 | ArcticDB: 1.3.0

**Comment by poodlewars** [comment]
LMDB does not support remote filesystems, so we don't expect this to work.

Search for "remote filesystems" in http://www.lmdb.tech/doc/ .

ArcticDB is designed with object storage like S3 as the first-class citizen. I would recommend using that rather than LMDB to share data across hosts. If you'd just like to test without a cloud provider, I believe there are ways to spin up S3-like storages without using a cloud provider, you might be interested in something like https://github.com/minio/minio , although we don't have experience with it.

**Comment by ivanli256138498** [comment]
Hi @poodlewars,

Thanks for your suggestion!

MinIO only recommends [Single-Node Single-Drive](https://min.io/docs/minio/windows/index.html). From your experience, is it possible to do that on Docker or k8s?

**Comment by qc00** [comment]
While we don't support LMDB on remote file systems, I have just tried it, and it appears to work for me.

Please check the user has permission to create directories and files in `arcticdb_lmdb_testing` directory and that it is exclusively used by Arctic (i.e. not contain other files and folders).
