### ISSUE TITLE
get_description_batch is really slow when you are loading thousands of symbols.

### ISSUE THREAD

**Issue by alokwatve** [man-group/ArcticDB#493]
**Is your feature request related to a problem? Please describe.**
get_description_batch takes about 30s for 100 symbols. We have more than 20K symbols. Is there a way to make it faster.

**Describe the solution you'd like**
Either get_description_batch should be fast (like list_symbols which automatically becaomes faster on subsequent calls) or there should be a way to "stream" data.

**Describe alternatives you've considered**
I am currently batching my symbol list manually:

```python
for chunk_of_X_symbols in symbol_list_of_20k_symbols:
    library.get_description_batch(chunk_of_X_symbols)
```
**Additional context**
n/a

**Comment by mehertz** [comment]
This should be roughly 10x faster since the release of 1.4. 

In your example, is it performant enough for 20k symbols?

**Comment by alokwatve** [comment]
I can confirm that for roughly 20K symbols it now takes about 5-6mins compared to 50 minutes in 1.3. so your claim about 10x performance gain sounds correct. Thanks for the improvements.
