### ISSUE TITLE
Data batch fetching by time zone Features

### ISSUE THREAD

**Issue by TianQingX** [man-group/ArcticDB#494]
Dear ArcticDB Fellows

**Is your feature request related to a problem? Please describe.**
I got three main feature for the Quant development
1. get all symbol data from each library by announcing time frame from time1 - time2
2. calculate the data for all the symbols for time1-time2 
3. Do you have suggested for Cross-Section Analysis (Cross symbols even libraries) for the same time zones 

**Describe the solution you'd like**
1. A clear and concise description of what you want to happen.
    def fetch_Batch(library, symbol = all, time = all)
2. Calculate by Arctic DB by pandas syntax and return the calculated data,
    def getdata_timezone(library = "" symbol = "",  time_start = " ", time_end = " ")
    def calculatedata_timezone(library = "" symbol = "",  time_start = " ", time_end = " ", func = function())

**Describe alternatives you've considered**
1-3. simply return the data required is also satisfied the basic research needs.

**Comment by poodlewars** [comment]
You can find all the symbols in a library with `list_symbols`.

Have you considered using `read_batch` and `list_symbols`?

You can find all the symbols in a library with `list_symbols`. You can then read data out by using `read_batch` with `ReadRequest` objects that specify your desired `date_range`.

https://docs.arcticdb.io/api/library#arcticdb.version_store.library.Library.read_batch
https://docs.arcticdb.io/api/library#arcticdb.version_store.library.Library.list_symbols

Or am I misunderstanding your request @TianQingX ?

I'll resolve this ticket for now, but please feel free to reopen if I haven't answered your question.
