### ISSUE TITLE
Enable metadata write at the same time as finalize_staged_data

### ISSUE THREAD

**Issue by willdealtry** [man-group/ArcticDB#515]
IN the C++ there is a user metadata parameter that allows metadata to be written at the same time as staged data is finalized. However, this is not currently exposed by the Python API, necessitating a call to finalize_staged_data followed by a call to write_metadata which is inefficient and unnecessary. 

We should expose the metadata parameter to the Python API.

**Comment by DerThorsten** [comment]
On the python side, `finalize_staged_data` calls into `compact_incomplete` which already has as `meta-data` argument.
https://github.com/man-group/ArcticDB/blob/4f2b4cb5e38f323d661a3564e2e8512c08b29372/python/arcticdb/version_store/_store.py#L1778

Is this the metadata you are talking about


Could you point me to the part of the C++ API ?
