### ISSUE TITLE
lib.delete_library doesn't remove the contents from disk

### ISSUE THREAD

**Issue by anno189** [man-group/ArcticDB#517]
Create a database using the lmdb mode。
ac.delete_ Library() without any error prompt, but the library file still exists on disk. Is this result correct?
lib. delete ('data '), the library file has not been reduced, is this result correct?

Snippet to reproduce:

```
In [3]: ac = arcticdb.Arctic('lmdb:///tmp/file')

In [4]: ac.create_library('test')

In [5]: lib = ac['test']

In [7]: lib.write_pickle('hello', 2)
Out[7]: VersionedItem(symbol='hello', library='test', data=n/a, version=0, metadata=None, host='LMDB(path=/tmp/file)')
```

Before running delete:

```
> ls -lR
.:
total 8
drwxr-xr-x 2 mhertz nscd 4096 Jul  4 15:44 _arctic_cfg
drwxr-xr-x 2 mhertz nscd 4096 Jul  4 15:44 test

./_arctic_cfg:
total 20
-rw-r--r-- 1 mhertz nscd 16384 Jul  4 15:44 data.mdb
-rw-r--r-- 1 mhertz nscd 65664 Jul  4 15:44 lock.mdb

./test:
total 56
-rw-r--r-- 1 mhertz nscd 53248 Jul  4 15:45 data.mdb
-rw-r--r-- 1 mhertz nscd 65664 Jul  4 15:45 lock.mdb
```

After running `ac.delete_library('test')`:

```
> ls -lR
.:
total 8
drwxr-xr-x 2 mhertz nscd 4096 Jul  4 15:44 _arctic_cfg
drwxr-xr-x 2 mhertz nscd 4096 Jul  4 15:44 test

./_arctic_cfg:
total 32
-rw-r--r-- 1 mhertz nscd 28672 Jul  4 15:45 data.mdb
-rw-r--r-- 1 mhertz nscd 65664 Jul  4 15:45 lock.mdb

./test:
total 56
-rw-r--r-- 1 mhertz nscd 53248 Jul  4 15:45 data.mdb
-rw-r--r-- 1 mhertz nscd 65664 Jul  4 15:45 lock.mdb
```

No change. 

This is on Linux.

**Comment by jjerphan** [comment]
Hello @anno189,

Thank you for this report.

Could you [craft a minimal reproducer](https://matthewrocklin.com/minimal-bug-reports) for this problem that can reproduce the error and report the output, exception or stack trace?

If the code is too long, feel free to put it in a [public gist](https://gist.github.com/) and link it in the issue.

We acknowledge that this requires some effort but it really helps us locate the problem.

**Comment by mehertz** [comment]
I'm able to reproduce. Added a snippet that is reproducable.

**Comment by poodlewars** [comment]
I've merged a fix for this @anno189 so it will be in the next release.

A limitation is that when you delete the last library in a path, the `_arctic_cfg` library will remain.
