### ISSUE TITLE
Add Azure conda support

### ISSUE THREAD

**Issue by phoebusm** [man-group/ArcticDB#519]
Related ticket: https://github.com/man-group/ArcticDB/issues/284

Awaiting conda support for Azure C++ sdk

**Comment by jjerphan** [comment]
Building `azure-identity` locally, one can see the dependencies to package.

`azure-identity` and `azure-storage-blobs` depend _at least_ on `azure-core` which is not packaged on conda-forge (there's just [an eponymous python package for the Python SDK]()).

Eponymous python packages exist on conda-forge:
 - [`azure-storage-blob`](https://anaconda.org/conda-forge/azure-storage-blob)
 - [`azure-identity`](https://anaconda.org/conda-forge/azure-identity)
 - [`azure-core`](https://anaconda.org/conda-forge/azure-core)

`azure-core` depends (transitively) on other packages like `azure-uamqp-c`, `azure-c-shared-utility`, `macro-utils-c` which are packaged on conda-forge. Yet some of them are only packaged for Windows and some others for everything else than Windows. See each project pages:
 - [`azure-uamqp-c`](https://anaconda.org/conda-forge/azure-uamqp-c)
 - [`azure-c-shared-utility`](https://anaconda.org/conda-forge/azure-c-shared-utility)
 - [`macro-utils-c`](https://anaconda.org/conda-forge/macro-utils-c)

**Comment by poodlewars** [comment]
There is an open PR for Azure on Conda - https://github.com/conda-forge/staged-recipes/pull/23297

**Comment by jdblischak** [comment]
Hi all - I'm the author of the staged-recipes PR for the Azure SDK for C++ (https://github.com/conda-forge/staged-recipes/pull/23297). I've addressed the first round of reviews, but I'm having difficult regaining momentum. To help push the PR along, I'd appreciate it if you could help out by doing any of the following (from least to most involved):

* Give a thumbs up to the PR
* Submit a review (with specific feedback or simply to approve if it looks good to you)
* Volunteer to be a co-maintainer of the recipe (if you post in the PR that you are willing to be a maintainer, I'll add you to the recipe)

**Comment by jjerphan** [comment]
Hi @jdblischak,

Thanks for mentioning this work!

I am currently off, but I can perform all your suggestions starting next week.

**Comment by phoebusm** [comment]
Plan:
If https://github.com/conda-forge/staged-recipes/pull/23297 is merged, azure sdk support will be added using conda. If not, we will try:
1. CMake Project + fetch content
2. Use Vcpkg in conda build

**Comment by jjerphan** [comment]
In addition to https://github.com/conda-forge/staged-recipes/pull/23297, we also need the dependencies to be available for all OSes; this is not the case for now for:
 - [azure-uamqp-c](https://anaconda.org/conda-forge/azure-uamqp-c)
 - [azure-c-shared-utility](https://anaconda.org/conda-forge/azure-c-shared-utility)
 - [azure-macro-utils-c](https://anaconda.org/conda-forge/azure-macro-utils-c)

I can work on that if we judge this becomes a priority.

**Comment by jdblischak** [comment]
> we also need the dependencies to be available for all OSes

@jjerphan does your use case require the AMQP protocol? Note that I purposefully avoided [azure-core-amqp](https://github.com/Azure/azure-sdk-for-cpp/tree/main/sdk/core/azure-core-amqp) in my staged-recipes PR. In other words, if you don't need AMQP support, I don't think you should need to worry about azure-uamqp-c and azure-c-shared-utility

**Comment by jjerphan** [comment]
I think @phoebusm can provide some information about that.

The transitive dependencies given in https://github.com/man-group/ArcticDB/issues/519#issuecomment-1629131296 were based on a local build performed locally, without adapting build options in details. Building without the support of AMQP would be useful.

**Comment by phoebusm** [comment]
@jjerphan At the moment, ArcticDB only requires 
[azure-storage-blob](https://anaconda.org/conda-forge/azure-storage-blob)
[azure-identity](https://anaconda.org/conda-forge/azure-identity)
[azure-core](https://anaconda.org/conda-forge/azure-core)

**Comment by jjerphan** [comment]
https://github.com/conda-forge/staged-recipes/pull/23297 has been merged, publishing all those libraries.

**Comment by phoebusm** [comment]
https://github.com/man-group/ArcticDB/pull/853 created for removing blocker of running azure-related conda build test
