### ISSUE TITLE
Stricter checking for Azure storage write and update if key exists/not exists

### ISSUE THREAD

**Issue by phoebusm** [man-group/ArcticDB#530]
Enhancement for https://github.com/man-group/ArcticDB/issues/284
Related https://github.com/man-group/ArcticDB/issues/447

Per this comment https://github.com/man-group/ArcticDB/pull/427#discussion_r1246364613 exception should be thrown if
1. key exists during `write()`
2. key does not exist during `update()`
Azure storage supports this conditional checking.

**Comment by poodlewars** [comment]
Won't do for now.l
