### ISSUE TITLE
When querying multiple symbols from arcticdb using read_batch, the whole query fails if one of the symbols is invalid

### ISSUE THREAD

**Issue by alokwatve** [man-group/ArcticDB#531]
**Is your feature request related to a problem? Please describe.**
Lets assume that I have saved three symbols s1, s2, and s3 to arcticdb. If I try to "read_batch" these symbols using the following it will fail
```
vesioned_items = lib.read_batch(["s1", "s2", "bogus"])
```
I get an exception: 
InternalException: E_ASSERTION_FAILURE Version not found for stream

There are two issues with this: (1) the exception does not tell me which symbol is invalid
(2) Ideally, we should get two valid versioned items with one error item.

**Describe the solution you'd like**
A list of versioned items where first two items are valid and we can read "data" field from them. Third item may either throw if I try to access "data" or may indicate the error in some other way.

**Describe alternatives you've considered**
Because the exception is not very explicit, we have to either try each symbol separately or do a list_symbols () followed by some python gymnastics to eliminate invalid symbol names.

**Additional context**
We end up with situations where a user may query for several symbols without realizing some of them are incorrect or just fat-fingering some names. We should be more graceful and only throw exceptions for symbols that are incorrect.

**Comment by poodlewars** [comment]
We discussed this in the team a while ago and thought that the following would be a sensible scheme, returning a `None` VersionedItem in the i-th entry of the result set to indicate an error for the i-th symbol.

![image](https://github.com/man-group/ArcticDB/assets/25333060/5c586887-425d-4e24-9280-c2a9f84c8126)

We'd need to decide whether we can make these (breaking) API changes.

**Comment by alokwatve** [comment]
Is it possible to add nothrow=True/False argument and return None only if the flag is True? That way existing flavors will not change. Another thought, can VersionedItem be extended to contain errors (if any). And setting data=None.That way arcticdb can be more explicit about why it is returning no data.

**Comment by mehertz** [comment]
> Is it possible to add nothrow=True/False argument and return None only if the flag is True? That way existing flavors will not change. Another thought, can VersionedItem be extended to contain errors (if any). And setting data=None.That way arcticdb can be more explicit about why it is returning no data.

This is possible, but we've decided against this to minimize the complexity of the API.

Let us know if this is a problem.
