### ISSUE TITLE
staged flag not working in write_batch

### ISSUE THREAD

**Issue by glennsuber** [man-group/ArcticDB#554]
### Describe the bug

When using staged=True in write_batch it appears that the symbols is never written to the staged area, and instead commits straight to the live version of the symbol

### Steps/Code to Reproduce
```python
from src.helpers.helpers import connect_to_db
from arcticdb.version_store.library import WritePayload


db = connect_to_db()
lib = db.get_library("EOD")
RLJ = lib.read("RLJ").data
payloads = [WritePayload("NKE", RLJ, {}), WritePayload("TTT", RLJ, {})]
lib.write_batch(payloads, staged=True, prune_previous_versions=True)
staged_symbols = lib.get_staged_symbols()
```
### Expected Results

I would expect the staged_symbols to contain a list of symbols in the staging area ("NKE", "RLJ"), however, it returns an empty set. 

When trying the same script with a regular write command, the functionality is as expected.

### OS, Python Version and ArcticDB Version

Python: 3.9.17 (main, Jun  6 2023, 20:11:04) 
[GCC 9.4.0]
OS: Linux-5.4.0-152-generic-x86_64-with-glibc2.31
ArcticDB: 1.4.1

### Backend storage used

AWS S3

**Comment by vasil-pashov** [comment]
Hey, I'm confirming that this is a reproducible bug. It is also reproducible with the LMDB backend as well. Adding it to the backlog. We will post here with updates.

**Comment by poodlewars** [comment]
Just noting that this issue is also reproducible on our old internal version of ArcticDB, so this is not a recent regression.
