### ISSUE TITLE
Batch read fails when filtering by columns

### ISSUE THREAD

**Issue by GemDot** [man-group/ArcticDB#563]
### Describe the bug

When we do a read batch trying to filter by columns, there is an internal exception regarding a coercing issue in the index type:

arcticdb_ext.exceptions.InternalException: E_ASSERTION_FAILURE Cannot coerce index type from TD<type=MICROS_UTC64, dim=0> to TD<type=INT8, dim=0>

### Steps/Code to Reproduce

Run this test (not currently in master): 

python -m pytest tests/integration/arcticdb/version_store/test_basic_version_store.py::test_batch_read_columns

```
def test_batch_read_columns(lmdb_version_store_tombstone_and_sync_passive):
    lmdb_version_store = lmdb_version_store_tombstone_and_sync_passive
    symbols = []
    for i in range(1):
        symbols.append("sym_{}".format(i))
    base_date = pd.Timestamp("2019-06-01")
    dfs = []
    for j in range(1):
        df = get_sample_dataframe(1000, j)
        df.index = pd.date_range(base_date + pd.DateOffset(j), periods=len(df))
        dfs.append(df)

    for x, symbol in enumerate(symbols):
        lmdb_version_store.write(symbol, dfs[x])

    result_dict = lmdb_version_store.batch_read(symbols, columns = [["int8"]])
    for x, sym in enumerate(result_dict.keys()):
        vit = result_dict[sym]
        assert_frame_equal(vit.data, dfs[x]["int8"])
```

### Expected Results

We want the column data for that dataframe

### OS, Python Version and ArcticDB Version

Python: 3.6.15 | packaged by conda-forge | (default, Dec  3 2021, 18:49:41) 
[GCC 9.4.0]
OS: Linux-5.15.0-72-generic-x86_64-with-centos-7.9.2009-Core
Using public ArcticDB. Set env var MAN_ARCTICDB_USE_ARCTICDB=false to use arcticc
ArcticDB: 1.4.1.dev0

**Comment by mehertz** [comment]
What data is in `get_sample_dataframe`? Is this always the case or just for that column?

**Comment by GemDot** [comment]
the bug for the batch_Read method when specifying columns is because the async_read_direct method, the position 0 of the frame refers to the first actual column rather than the index column, which is what we expect. In the non-batch version, the index is added to the set of columns of the queries.
