### ISSUE TITLE
Suppress the warning about nanoseconds being ignored. 

### ISSUE THREAD

**Issue by alokwatve** [man-group/ArcticDB#569]
**Is your feature request related to a problem? Please describe.**
When querying arcticdb we often see the following warning:

```
arcticdb/version_store/_store.py:2252: UserWarning: Discarding nonzero nanoseconds in conversion
  _from_tz_timestamp(max_ts, "UTC").astimezone(pytz.timezone(tz)),
```
There is very little a user can do about it but it may spook a naive user.

**Describe the solution you'd like**
There should be a way to suppress this warning.

**Describe alternatives you've considered**
None

**Comment by jjerphan** [comment]
Hi @alokwatve, 

Thank you for reporting this issue, which version of ArcticDB and pandas are you using?
