### ISSUE TITLE
E_ASSERTION_FAILURE should be a catchable exception instead of a log message.

### ISSUE THREAD

**Issue by alokwatve** [man-group/ArcticDB#576]
**Is your feature request related to a problem? Please describe.**
If the symbol client is querying for is not available in arcticdb, we current see an error message:
"E_ASSERTION_FAILURE Version not found for stream"
While this is useful, it is not a catchable exception, so we cannot take some reasonable action on it. One possible action could be to catch the exception and print it in more user friendly way like "Symbol you are requesting is not available"

**Describe the solution you'd like**
Make this a catchable exception instead of just a log message.

**Describe alternatives you've considered**
None/

**Additional context**
n/a

**Comment by mehertz** [comment]
With the release of 1.6.1rc0 is this still an issue?
