### ISSUE TITLE
Missing data errors throw different exception types

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#591]
### Describe the bug

Missing data has multiple differing exception types:

```
line 1586, in _read_dataframe
    return ReadResult(*self.version_store.read_dataframe_version(symbol, version_query, read_query, read_options))
arcticdb_ext.storage.NoDataFoundException: <symbol>
```

```
line 1586, in _read_dataframe
    return ReadResult(*self.version_store.read_dataframe_version(symbol, version_query, read_query, read_options))
arcticdb_ext.exceptions.StorageException: Composite: d:BBG00GD1JMY1/None:544:0x1d6d9bb0060ab3d3@1688984724249616469[1688563800000000000,1688759940000000001],
```

Both examples are because data is missing, but they return different exceptions with different hierarchies.

### Steps/Code to Reproduce

Delete the data key for for the Composite error

Read a symbol that doesn't exist for the first error

### Expected Results

Both exceptions are catchable with the same root class.

### OS, Python Version and ArcticDB Version

All versions

### Backend storage used

All storages

**Comment by muhammadhamzasajjad** [comment]
Hi @mehertz. In regards to the second exception you reported, currently, if a data key is deleted and then the related symbol is read using `Library`, the exception `arcticdb_ext.storage.NoDataFoundException` is thrown instead of `arcticdb_ext.exceptions.StorageException`.
