### ISSUE TITLE
Make QueryBuilder type promotions safer

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#594]
**Is your feature request related to a problem? Please describe.**

The type calculated by `type_arithmetic_promoted_type` is not big enough when one/both arguments are `[u]int64`.

This is especially noticeable for multiply and divide operations where the result might overflow to be smaller/bigger than the operands.

> For example, the QueryBuilder expression `q[q["uint64 col A"] * q["uint64 col B"] > q["uint64 col A"]]` should logically return all rows. However, given the promoted type is calculated to be `uint64_t`, the multiplication can overflow and make the relationship false.

For the `Is[Not]InOperator`, we applied special handling, but not for the others.

**Possible solutions**

* Use `double` as the promoted type (convert both arguments to `double` before operation)
* Use an `int128` type as the promoted type (from our Decimal work)
* Keep the arguments' original types, but allow the return type to be `variant<uint64, double>`

**Comment by alexowens90** [comment]
This is a deliberate choice. We accept the `if` statements in set membership operations as there is a hash involved anyway, which is expensive. For binary arithmetic operations, we deliberately took the choice to always keep integers as integers, and accept that overflow is a possibility when [u]int64_t's are involved.
