### ISSUE TITLE
Synology C2 Object Storage support

### ISSUE THREAD

**Issue by femtotrader** [man-group/ArcticDB#630]
Hello,

Synology provide an inexpensive S3 like storage named C2 Object Storage.
https://c2.synology.com/
https://c2.synology.com/en-global/object-storage/overview
They say "Compatible with Amazon S3 API / Use your existing tools and code as our API is S3-compatible."
See https://kb.synology.com/en-global/C2/tutorial/C2_Object_Storage_Compatible_API
I'm wondering if ArcticDB can support it
If it doesn't it could be great to have such a support added.

Kind regards

**Comment by femtotrader** [comment]
Terminaison point looks like https://eu-002.s3.synologyc2.net

So I tried

    from arcticdb import Arctic
    url = "s3://synologyc2.net:crypt-hist?region=eu-002&access=MyKeyId&secret=MySecretKey"
    client = Arctic(url)
    client.create_library('data')

but it raises an `UnexpectedS3ErrorException`

```
ingest2arcticdb-py-script-1  |     if self._library_manager.has_library(name):
ingest2arcticdb-py-script-1  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ingest2arcticdb-py-script-1  | arcticdb_ext.exceptions.InternalException: arcticdb::storage::s3::detail::UnexpectedS3ErrorException(std::exception)
```

**Comment by poodlewars** [comment]
Hi 👋 Thanks for trying ArcticDB.

I was able to connect to Synology C2 OK from ArcticDB.

```python
In [1]: from arcticdb import Arctic

In [2]: endpoint = "https://eu-002.s3.synologyc2.net"

In [3]: access ="<REDACTED>"

In [5]: secret = "<REDACTED>"

In [6]: uri = f"s3://{endpoint}:aseaton-test?access={access}&secret={secret}"

In [7]: ac = Arctic(uri)

In [8]: ac.list_libraries()
Out[8]: []

In [9]: ac.create_library("tst")

In [10]: ac.list_libraries()
Out[10]: ['tst']

In [11]: import pandas as pd

In [12]: df = pd.DataFrame({"d":[1,2,3]})

In [13]: l = ac["tst"]

In [14]: l.write("symbol", df)
Out[14]: VersionedItem(symbol='symbol', library='tst', data=n/a, version=0, metadata=None, host='S3(endpoint=https://eu-002.s3.synologyc2.net, bucket=aseaton-test)')

In [15]: l.read("symbol")
Out[15]: VersionedItem(symbol='symbol', library='tst', data=<class 'pandas.core.frame.DataFrame'>, version=0, metadata=None, host='S3(endpoint=https://eu-002.s3.synologyc2.net, bucket=aseaton-test)')

In [16]: l.read("symbol").data
Out[16]:
   d
0  1
1  2
2  3
```

This is on Windows:

```python
In [17]: import arcticdb

In [18]: arcticdb.__version__
Out[18]: '1.5.0'

In [19]: import platform

In [20]: platform.platform()
Out[20]: 'Windows-10-10.0.19044-SP0'

In [21]: import sys

In [22]: sys.version
Out[22]: '3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]'
```

Let me know if that helps. If you still can't connect, please share the info above about your platform and I can try to repro on a system like your's.

**Comment by femtotrader** [comment]
Hi @poodlewars ,

Looks good now ! Thanks for your help. I was probably mistaken about uri.
Sorry about that

Kind regards

**Comment by femtotrader** [comment]
My problem was that I didn't understood that uri looks like

    uri=f"s3://https://{region}.s3.synologyc2.net:{bucket}?access={access}&secret={secret}"

ie https:// after s3://

Thanks again
