### ISSUE TITLE
Generate code coverage

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#638]
### What?

Generate and report on test coverage.

### Why?

Features that reduce our test coverage are invisible. If it were visible, we could ensure all PRs result in an increase in terms of code coverage.

### Solution Ideas

Possible ideas,

- [ ] Enable [Gcov](https://en.wikipedia.org/wiki/Gcov) ?
- [ ] Use [Code Coverage Report](https://github.com/marketplace/actions/code-coverage-report) to make the coverage visible?

### Comments

This might slow down our tests. We may not be able to run it on every branch build, and may need more powerful test runners.

**Comment by poodlewars** [comment]
Maybe consider https://github.com/gcovr/gcovr

**Comment by poodlewars** [comment]
Findings: https://github.com/man-group/ArcticDB/wiki/Development-Documentation:-Code-Coverage-Findings
