### ISSUE TITLE
`as_of` with a timestamp is slower to resolve compared to direct version access with `read_batch`

### ISSUE THREAD

**Issue by alexowens90** [man-group/ArcticDB#649]
Ongoing work for this in this branch:
https://github.com/man-group/ArcticDB/compare/master...store_penultimate_version_in_map

With `read_batch`, the load parameter is correctly set to include a timestamp, but this information isn't used to exit the while loop, so the entire version chain is always loaded. As a result, `read_batch(as_of=<datetime>)` is slower than `read_batch(as_of=-5)` despite returning the same version.

**Comment by willdealtry** [comment]
This is addressed in https://github.com/man-group/ArcticDB/pull/596

**Comment by mehertz** [comment]
This feels like two bugs?

1. ...this information isn't used to exit the while loop, so the entire version chain is always loaded....
2. ...also keep going back through the chain until a live version is reached...

If so I think we should track the second issue seperately.

**Comment by mehertz** [comment]
I see you've created #661 . Thank you. I'm going to update the description of this ticket.
