### ISSUE TITLE
`as_of` with a timestamp always loads entire version chain with non-batch `read`

### ISSUE THREAD

**Issue by alexowens90** [man-group/ArcticDB#661]
Ongoing work for this in this branch:
https://github.com/man-group/ArcticDB/compare/master...store_penultimate_version_in_map

`get_all_versions` is called, which uses the load parameter `LOAD_ALL`.

**Comment by mehertz** [comment]
> which uses the load parameter LOAD_ALL.

...and as a result we might return deleted data?

#649 is a performance improvement, and fixing this issue ensures we always return valid data - right?
