### ISSUE TITLE
`date_range=(None, None)` raises an error when reading non-timeseries symbols

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#677]
### Describe the bug

When reading non-timeseries symbols, `date_range=(None, None)` raises an exception.

`date_range=(None, None)` should be equivalent to `date_range=None` though, so this should not be the case.

### Steps/Code to Reproduce

```
In [21]: df = pd.DataFrame({'hello': ['world']})

In [22]: lib.write('test', df)
Out[22]: VersionedItem(symbol='test', library='test2', data=n/a, version=2, metadata=None, host='LMDB(path=/tmp/lmdbtest2)')

In [23]: res = lib.read('test', date_range=(None, None))
[2023-07-31 16:51:59.500] [arcticdb] [error] E_ASSERTION_FAILURE Cannot apply date range filter to symbol with non-timestamp index
```

### Expected Results

All the data is returned as `date_range=(None, None)` should be equivalent to `date_range=None`.

### OS, Python Version and ArcticDB Version

1.5.0, 1.6.0, 1.6.1

### Backend storage used

Any

### Additional Context

Any

**Comment by poodlewars** [comment]
I'm going to close this as won't fix. It isn't obvious which API is better, I slightly prefer the current one as `date_range=(None, None)` on non-ts symbol seems likely to be a programming or data error.

Also, in Python the two arguments have different truthiness:

```
In [22]: bool((None, None))
Out[22]: True

In [23]: bool(None)
Out[23]: False
```

I think the current API is defensible.
