### ISSUE TITLE
Set up sanitizers in build process

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#680]
### What?

Enable use of [https://github.com/google/sanitizers](https://github.com/google/sanitizers) in our CMake build.

### Why?

This will help us address issues before that would otherwise escape our testing.

### How?

Probably by modifying our CMake toolchains as per this [Reddit comment](https://www.reddit.com/r/cpp/comments/lmj32h/comment/gnw2tez/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button). 

### Comments

This issue doesn't track the addition of running the sanitized code in our tests. This is tracked in #13.

**Comment by poodlewars** [comment]
Discuss with @willdealtry 

This is to be able to run sanitizers locally with our normal tests. Should include docs for devs on how to do it.

William thinks may be easier if we upgrade GCC to 11+ first, or just build with clang which bundles sanitizers.
