### ISSUE TITLE
`as_of=Timestamp(...)` searches in snapshots

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#682]
### Describe the bug

Any operation (`read`, etc.) that accepts `Timestamp` as a way to locate a version will currently search through all the snapshots if there are no live versions available.

This is probably for backwards compatibility with Arctic Python, but it is slow.

This feature is probably unexpected for external users, so we should hide it behind a library option that's enabled for internal users only.

**Comment by mehertz** [comment]
Removed `and is not reliable`. Not aware if any isues regarding that.
