### ISSUE TITLE
how to append_batch or update_batch?

### ISSUE THREAD

**Issue by zzxfriend** [man-group/ArcticDB#698]
I found that there is a write_batch method that can write data in batches, but it will overwrite the previous data,I want to implement the update or append method to update the data rather than overwrite. Is there a fast batch writing method?

**Comment by zzxfriend** [comment]
sry, I still dont find this method,I can only find read_batch and write_batch ,how can I call the append_batch method?
<img width="534" alt="image" src="https://github.com/man-group/ArcticDB/assets/56020647/9fce4ceb-31d6-4a69-acdc-b5d199f8c02d">

**Comment by zzxfriend** [comment]
I am using s3 storage

**Comment by GemDot** [comment]
You will have access to it once #534 is completed. There is already a change implementing it, which will be merged very soon. Once it is merged, it will be published in the next release and you will then have access to the method.

**Comment by zzxfriend** [comment]
ok , i am looking forward to it.

**Comment by GemDot** [comment]
https://github.com/man-group/ArcticDB/issues/700

this is a ticket for batch_update, but there is no a ETA for it.

**Comment by jamesmunro** [comment]
#534 is closed.

**Comment by poodlewars** [comment]
I'll resolve this one as a duplicate now. @zzxfriend - please could you subscribe to #700 for news about `update_batch`?
