### ISSUE TITLE
Arcticdb import started failing for 1.6.1

### ISSUE THREAD

**Issue by alokwatve** [man-group/ArcticDB#733]
### Describe the bug

Arcticdb 1.6.1 was working fine until last Friday. Some time over the weekend we have started seeing this error:

```
/opt/conda/lib/python3.9/site-packages/arcticdb/__init__.py:1: in <module>
    import arcticdb_ext as _ext
E   ImportError: /opt/conda/lib/python3.9/site-packages/arcticdb_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNK5folly7futures6detail8CoreBase11getExecutorEv
collected 0 items / 1 error
```

### Steps/Code to Reproduce

```python
import arcticdb
```

### Expected Results

No exception should be thrown and import should succeed.

### OS, Python Version and ArcticDB Version

We are using Python3.9 on linux ... The command above fails due to the import error. But we are using arctcidb 1.6.1

### Backend storage used

S3

**Comment by jamesmunro** [comment]
Work around merged. https://github.com/conda-forge/arcticdb-feedstock/pull/44
