### ISSUE TITLE
Run all existing tests against real storages too in the CI

### ISSUE THREAD

**Issue by poodlewars** [man-group/ArcticDB#743]
We should try just running all the existing tests against real storages in the CI and checking the cost is reasonable, since it hasn't been very expensive so far.

We can do it by swapping out the s3 fixture used from the simulator to real storage, in a dedicated (once a day?) job.

**Comment by G-D-Petrov** [comment]
Do we want to have option to parametrize the existing tests to support small/medium/ large data (similar to [this](https://github.com/man-group/ArcticDB/blob/master/python/tests/stress/arcticdb/version_store/test_stress_dynamic_bucketize.py#L17))

Or do we want totally new tests that are specifically running with large data?
