### ISSUE TITLE
Extend real storage tests to run with large lifelike data and all API methods

### ISSUE THREAD

**Issue by poodlewars** [man-group/ArcticDB#744]
It would be good to extend the tests to run with more lifelike large data and a bigger variety of our methods. For LMDB, we always thought it was fine as it passed all the tests, but actually in practice once you write large data to it it blew up.

**Comment by G-D-Petrov** [comment]
Do we want to extend the current tests to run with variable sized data (something similar to [this](https://github.com/man-group/ArcticDB/blob/master/python/tests/stress/arcticdb/version_store/test_stress_dynamic_bucketize.py#L17))

Or do we want totally new tests specifically made for large data?

**Comment by poodlewars** [comment]
It would be good to make sure we have coverage for:

- Append
- Update
- Delete
- Batch methods
- Staged data
- Compaction `defragment_symbol_data` and `is_symbol_fragmented`
- Symbol list and symbol list compaction

all with realistically large data. Re-using (maybe re-parameterizing) existing tests seems like a good way to do this where possible, and we can write bespoke new tests where it isn't.

We should make sure we cover dynamic schema, sparse data and query builder queries as well.

Of course some of this might already be covered fine by the existing real storage tests, but we should check.

https://github.com/man-group/ArcticDB/blob/master/docs/mkdocs/docs/technical/contributing.md#development-guidelines
