### ISSUE TITLE
ArcticDB conda-forge build dynamically links against ABI-unstable libraries for Linux/MacOS

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#765]
### What is the problem?

When building the conda-forge release, we have the following runtime binary dependencies:

```
    - glog
    - folly <=2023.08.07.00
    - aws-crt-cpp >=0.19.8
    - prometheus-cpp
    - protobuf
    - lmdb
```

Not all of these libraries guarantee ABI stability between versions. In other words, we must runtime-depend on the version we build against.

Currently this is not the case. If any of the above libraries updates and the new version is not ABI compatible with the version ArcticDB was built against, you will get an error on import. For example (for Folly):

```
    # E   ImportError: .../arcticdb_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: 
    # _ZNK5folly7futures6detail8CoreBase11getExecutorEv
```

### What can we do to fix the issue?

We should statically link (vendoring) all C++ dependencies that don't guarantee ABI compatibility. **We will need to shade all included symbols**. Our current solution is to pin folly against the same version we build against but if any other packages depend on a different version of Folly we might not be able to fully resolve the dependency graph so this is not a long term solution. 

### Other comments

Our PyPI build already does exactly this (statically linking). It may be worth re-using that for conda-forge rather than building from scratch.

**Comment by jjerphan** [comment]
Let's try adapting folly's feedstock to also build the static library and switch to this one for ArcticDB?

**Comment by alexowens90** [comment]
We should also pin the other dependencies mentioned above to specific versions (the same as in vcpkg ideally) to prevent this issue from happening again with a different dependency.

**Comment by jjerphan** [comment]
This might also help #190 regarding dynamic linking issues observed with protobuf on Windows (see https://github.com/man-group/ArcticDB/pull/449/commits/d00fbd5cea8535f2144a1784364e0526289d4c9d).

**Comment by jjerphan** [comment]
https://github.com/conda-forge/folly-feedstock/pull/127 aims at adapting the setup to produce static libraries for Unix.

**Comment by jjerphan** [comment]
We must check that feedstocks correctly [export runtime requirements using `run_exports`](https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#export-runtime-requirements) with pin version to make sure they are using the same ABI.

The following feedstock from the package listed above export runtime requirements as follows:
 - [`glog`'s pins minor versions](https://github.com/conda-forge/glog-feedstock/blob/main/recipe/meta.yaml#L19-L22)
 - [`aws-crt-cpp`'s pins patch versions](https://github.com/conda-forge/aws-crt-cpp-feedstock/blob/main/recipe/meta.yaml)
 - [`prometheus-cpp`'s pins minor versions](https://github.com/conda-forge/prometheus-cpp-feedstock/blob/main/recipe/meta.yaml#L18-L19)
 - [`lmdb`'s pins patch version](https://github.com/conda-forge/lmdb-feedstock/blob/main/recipe/meta.yaml#L15-L16)

Also [`protobuf` depends on `libprotobuf`](https://github.com/conda-forge/protobuf-feedstock/blob/main/recipe/meta.yaml#L44) which also [exports runtime requirements pinning patch versions](https://github.com/conda-forge/libprotobuf-feedstock/blob/main/recipe/meta.yaml#L34-L38)

The feedstock of `folly` does not export runtime requirements but it must on the exact same version.

**Comment by jjerphan** [comment]
Just trying to see how this could be possible after having found https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/issues/224.

**Comment by jjerphan** [comment]
For now, we have a pin on the upper version for folly because the build variants on `libevent` have to use different versions of `folly` due to constraints.

Do you know if pinning versions of `folly` conditionally to the version of `libevent` is possible?

**Comment by jjerphan** [comment]
> Do you know if pinning a library conditionally to another one (e.g. here pinning folly depending on the version of libevent) is possible?

It is actually possible using [`zip_keys`](https://docs.conda.io/projects/conda-build/en/stable/resources/variants.html#special-variant-keys), but this is somewhat limited for python packages.

An easier path is to rebuild the versions of folly which are used to compile ArcticDB's variants and to recompile ArcticDB once they are published. Looking at [1.6.1 CI runs' logs](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=761915&view=logs&j=8ca717d7-2f91-593f-2e86-7b14f42b0119), two versions of folly are used:
 - `2023.03.20.00` is used by the `libevent 2.1.10` builds, https://github.com/conda-forge/folly-feedstock/pull/133 updates this version
 - `2023.08.07.00` is used by the `libevent 2.1.12` builds, https://github.com/conda-forge/folly-feedstock/pull/132 updates this version

Once those two PRs are merged, I'll open two more to bump the build number on:
 - https://github.com/conda-forge/arcticdb-feedstock/tree/main
 - https://github.com/conda-forge/arcticdb-feedstock/tree/rc

**Comment by jjerphan** [comment]
To me, this issue has been fixed by the distribution of new builds as shown above.

I let @mehertz verify and close.

---

Also regarding this comment for over-/under-linkage checks:

> Furthermore, it might be worthwhile to have over-/under-linkage checks activated to ensure that all direct dependencies of ArcticDB are listed in the recipe. conda-build currently prints the information if a direct dependency is missing as an informative output but doesn't error on it by default.

For know, [we mainly have warnings for over-linkage but None for missing dependencies](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=761915&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7&l=1442):

```
WARNING (arcticdb): plugin library (Python) package conda-forge::grpcio-tools-1.54.2-py310hc6cd4ac_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (arcticdb): run-exports library package conda-forge::cyrus-sasl-2.1.27-h9033bb2_6 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (arcticdb): run-exports library package conda-forge::krb5-1.20.1-h81ceb04_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (arcticdb): run-exports library package conda-forge::libevent-2.1.10-h28343ad_4 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (arcticdb): run-exports library package conda-forge::gtest-1.14.0-h00ab1b0_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (arcticdb): run-exports library package conda-forge::msgpack-c-6.0.0-hfc55251_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (arcticdb): run-exports library package conda-forge::xxhash-0.8.2-hd590300_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (arcticdb): run-exports library package conda-forge::gflags-2.2.2-he1b5a44_1004 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (arcticdb): plugin library (Python) package conda-forge::protobuf-4.21.12-py310heca2aa9_0 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (arcticdb): run-exports library package conda-forge::double-conversion-3.2.0-h27087fc_1 in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
WARNING (arcticdb): interpreter (Python) package conda-forge::python-3.10.12-hd12c33a_0_cpython in requirements/run but it is not used (i.e. it is overdepending or perhaps statically linked? If that is what you want then add it to `build/ignore_run_exports`)
```

I think we can clarify over-/under-linkage and activate the checks as part of nother issues and PRs. What do you think?

**Comment by jjerphan** [comment]
Closing since it has been marked as "Done" in [ArcticDB Planning](https://github.com/orgs/man-group/projects/3).
