### ISSUE TITLE
Documentation for QueryBuilder

### ISSUE THREAD

**Issue by poodlewars** [man-group/ArcticDB#786]
A docs (not API) page and tutorial describing how to use QueryBuilder, its caveats, and motivate users to understand why it is useful.

**Comment by jamesmunro** [comment]
We now have: https://docs.arcticdb.io/latest/notebooks/ArcticDB_demo_querybuilder/
along with a number of blog post examples.

Closing, please re-open if you think there is a significant gap remaining.
