### ISSUE TITLE
Clearing a library clears all objects in a folder in AWS when a path_prefix is used 

### ISSUE THREAD

**Issue by G-D-Petrov** [man-group/ArcticDB#806]
### Describe the bug

When we use the path_prefix and we are using AWS S3, clearing a library results in all object under that path_prefix to be cleared.
I don't think that this is intended as this issue doesn't reproduce when we are using other local backends or when we use AWS S3 without passing a value for the path_prefix.

### Steps/Code to Reproduce

The easiest way to reproduce this is to run the following stress test:
tests/stress/arcticdb/version_store/test_stress_delete.py::test_stress_delete

And to use a the real_s3_store_factory as the factory for the test.
Right now this test fails when we use this factory, as it is passing a path_prefix.

### Expected Results

The test should pass with the real_s3_store_factory without any other changes.

### OS, Python Version and ArcticDB Version

Python: 3.8.10 (tags/v3.8.10:3d8993a, May 3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
OS: Windows-10-10.0.19044-SP0
ArcticDB: 1.4.1.dev0

### Backend storage used

AWS S3

### Additional Context

This problem reproduces only when we are using a NativeVersionStore object directly.
If we go through the regular flow of creating an Arctic object, creating a library, etc. this works correctly.

**Comment by poodlewars** [comment]
PR #789 includes a fix for this
