### ISSUE TITLE
slack goes down and cannot submit join forms

### ISSUE THREAD

**Issue by zeddit** [man-group/ArcticDB#809]
### Describe the bug

when submit join request on official website, it pops out and says below:
```
Error during submitting form
Some error occured :( Try again!
```

### Steps/Code to Reproduce

1. open https://arcticdb.io/ 
2. click community
3. click Join our Slack space
4. fill the form and submit
5. the error pops and cannot get into the slack.

### Expected Results

join successfully.

### OS, Python Version and ArcticDB Version

none

**Comment by jamesmunro** [comment]
Thanks for letting us know.  I've managed to reproduce.  We'll get this working again.  If you could send the same details the form expects to arcticdb@man.com we will try and add you on Slack.  Thanks.

**Comment by jamesmunro** [comment]
This is working again.  Thanks for letting us know.  Closing issue.
