### ISSUE TITLE
LMDB libraries are unreadable once moved

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#850]
### Describe the bug

The full path is stored in the library config protobuf

### Steps/Code to Reproduce

Create a library in a new folder using LMDB -> move/rename containing folder -> library not readable

### Expected Results

The library is readable.

### OS, Python Version and ArcticDB Version

All

### Backend storage used

LMDB

**Comment by poodlewars** [comment]
This was raised by a user in Slack https://arcticdb.slack.com/archives/C047WF34V7E/p1694449570998269 . We should let him know when this is fixed.
