### ISSUE TITLE
MinIO Support For Windows

### ISSUE THREAD

**Issue by jamesmunro** [man-group/ArcticDB#859]
### Describe the bug

Failed to write s3 with key when connected to minio hosted on Windows

> ac.create_library('baba') 
> arcticdb_ext.exceptions.InternalException: E_ASSERTION_FAILURE Failed to write s3 with key 'C:baba' XMinioInvalidObjectName: Unable to parse ExceptionName: XMinioInvalidObjectName Message: Object name contains unsupported characters.

### Steps/Code to Reproduce

- Start a minio server on windows.
- Connect to that server from ArcticDB.
- Create a library.

### Expected Results

Expected:  No error

### OS, Python Version and ArcticDB Version

Client environment not known

### Backend storage used

Minio on Windows

**Comment by poodlewars** [comment]
Could be because of this https://github.com/minio/minio/issues/3390#issuecomment-264666282

**Comment by poodlewars** [comment]
Minio does, however, work on Linux.

**Comment by poodlewars** [comment]
Closing as not planned - hosting the MinIO instance on Linux works OK, and we would need to change our data layout to support it on Windows.
