### ISSUE TITLE
Incorrect batch size limit for Azure

### ISSUE THREAD

**Issue by phoebusm** [man-group/ArcticDB#879]
### Describe the bug

Azure patch size limit should be 256 instead of 1000. It causes the `list_symbol()` silently fails.

### Steps/Code to Reproduce

```
for i in range(200):
    lib.write(f"{i}", 23)
    lib.write(f"{i}", 24)
for i in range(150):
    lib.delete(f"{I}")
lib.list_symbols()
```

### Expected Results

`E_ASSERTION_FAILURE Failed to create azure segment batch remove request 400: The batch operation exceeds maximum number of allowed subrequests.` will be printed but no exception will be thrown.

### OS, Python Version and ArcticDB Version

All

### Backend storage used

Azure

**Comment by jamesmunro** [comment]
@phoebusm ok to close this now?

**Comment by phoebusm** [comment]
@jamesmunro Closed as the fix has been merged and released
