### ISSUE TITLE
Open-ended DateRange causes Pandas OutOfBoundsDatetime

### ISSUE THREAD

**Issue by qc00** [man-group/ArcticDB#88]
We use `pandas.Timestamp.{min,max}` to represent open-ended date ranges, but that triggers a [bug](https://github.com/pandas-dev/pandas/pull/47268) in Pandas prior to version 1.5.0.

**Comment by mehertz** [comment]
Resulting exception:

```
OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 1677-09-21 00:12:43
```

**Comment by phoebusm** [comment]
The fix is already in-place in the master branch ([Link](https://github.com/man-group/ArcticDB/blob/61dac03a69d8b479957205c3d7732331a5cb9d4b/python/arcticdb/version_store/_normalization.py#L1280-L1281))
It will be included in the next release.
