### ISSUE TITLE
string values compare to NaN in QueryBuilder() case InternalException

### ISSUE THREAD

**Issue by TianQingX** [man-group/ArcticDB#890]
### Describe the bug

InternalException: E_ASSERTION_FAILURE Cannot compare TD to TD (possible categorical?)

it works on comparing int to nan but fail on comparing string, btw did you know how to compare to none?

![image](https://github.com/man-group/ArcticDB/assets/40229906/616041ac-bb12-4c5c-81fe-e9315c4ebb3f)

![image](https://github.com/man-group/ArcticDB/assets/40229906/dc83822a-e61d-41d8-b45c-dae27b9a89c9)

q = QueryBuilder()
q = q[(q[label] != None]
this will cause another error
![image](https://github.com/man-group/ArcticDB/assets/40229906/52e234a7-6ac0-437e-be6b-7d76c1704da2)

### Steps/Code to Reproduce

symbol = "CZCE.MA_1min.csv"
q = QueryBuilder()
label = "30-60: Up_or_Down"
q = q[(q[label] != None)] or Np.NaN
dataframe = lib.read(symbol, query_builder=q).data

### Expected Results

it should be work when filtering non nan value in string values type columns

### OS, Python Version and ArcticDB Version

Python: 3.9.13 (main, Aug 25 2022, 23:26:10) 
[GCC 11.2.0]
OS: Linux-6.2.0-26-generic-x86_64-with-glibc2.35
ArcticDB: 2.0.0

**Comment by jamesmunro** [comment]
Hi

Thanks for raising this.  It isn't supported right now.
> Restrictions:
> String equality/inequality (and isin/isnotin) is supported for printable ASCII characters only.
https://docs.arcticdb.io/api/query_builder

This would be a good feature.  We will look at adding it.

**Comment by TianQingX** [comment]
btw if comparing to the nan it can run but return no-working result,but it works can compare to Int, it still helps me when i fillna with same certain value to represent NaN. Many Thanks~
![image](https://github.com/man-group/ArcticDB/assets/40229906/64a50255-e0a7-4bc7-893f-5be5026b7b83)

**Comment by alexowens90** [comment]
I've opened a ticket https://github.com/man-group/ArcticDB/issues/902
