### ISSUE TITLE
0-row DataFrames are pickled regardless of library settings or API call used

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#90]
If you write a 0-row DataFrame, it is pickled even when using the `write` call.

Rather than pickling this, we should reject this unless written via `write_pickled`.

**Comment by jjerphan** [comment]
I think this has been addressed by https://github.com/man-group/ArcticDB/pull/646 and https://github.com/man-group/ArcticDB/pull/804 and can be close. For instance, see this test which assert the new behavior (there are other similar ones in `python/tests/unit/arcticdb/version_store/test_empty_writes.py`):

https://github.com/man-group/ArcticDB/blob/3f32c000d36e9359820e1352fedb7fe18ff30df8/python/tests/unit/arcticdb/version_store/test_empty_writes.py#L16-L21

@mehertz: can we close this issue as completed, or are there anything left to do?

**Comment by qc00** [comment]
@jjerphan There are two problems:

* Empty data frames need pickling. This has been addressed.
* The code incorrectly falls back to pickling even if the call is `write` not `write_pickled`. This has not been addressed.

Given we have separate issues for the first problem, I think this bug should be reworded to focus on the latter.

**Comment by jjerphan** [comment]
> The code incorrectly falls back to pickling even if the call is write not write_pickle. This has not been addressed.

Is this tracked by #91?

**Comment by jjerphan** [comment]
> The code incorrectly falls back to pickling even if the call is `write` not `write_pickle`. This has not been addressed.

I think this is tracked by #91, or is this different?

**Comment by poodlewars** [comment]
Resolving this one as left over work is covered by #91
