### ISSUE TITLE
Possible to pickle even outside of `write_pickle` and with `pickle_on_failure=False`

### ISSUE THREAD

**Issue by mehertz** [man-group/ArcticDB#91]
Pickling should be explicit rather than implicit. 

Either the call should be to normalize and write, or to pickle and write. Current code tries to normalize, and if it can't be normalize goes through multiple fallback steps to find a mechanism of writing to storage. 

This should be flipped on its head and made explicit.

**Comment by jjerphan** [comment]
In the case normalization fails for writing, must ArcticDB just err with a clear explicit error instead of pickling the object?

**Comment by qc00** [comment]
This is a dup of #223

**Comment by alexowens90** [comment]
There is an enhancement to make `Library.write` support types that are msgpack-serializable without pickling, but otherwise the current behaviour is as expected.
