### ISSUE TITLE
RocksDB Backend

### ISSUE THREAD

**Issue by poodlewars** [man-group/ArcticDB#913]

**Comment by joe-iddon** [comment]
Implement a new RocksDB backend.

Documentation and reference material:
- Documentation of RocksDB is [on Facebook's GitHub Wiki](https://github.com/facebook/rocksdb/wiki).
- The [Basic Operations](https://github.com/facebook/rocksdb/wiki/Basic-Operations) section is a good starting point.
- A good guide to the internals can be found [here](https://artem.krylysov.com/blog/2023/04/19/how-rocksdb-works/).

Relevant PRs are:
- #945  - C++ backend work + unit test
- #961 - Fixing dependency problems on Mac/Conda build
- #991 - Python API

**Comment by poodlewars** [comment]
Won't do for now
