### ISSUE TITLE
Improvements to defragment_symbol_data: Incorrect symbol list use and error-prone API

### ISSUE THREAD

**Issue by phoebusm** [man-group/ArcticDB#922]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
1. In function `defragment_symbol_data()`
- 
```
if(cfg_.symbol_list())
        symbol_list().add_symbol(store_, stream_id);
```
Is not needed as only existing symbol will be updated

2. Export `segment_row_size` in `LibraryOptions` and remove `segment_size` in the function parameter
- segment size should not be changed as it will lead to massive segment re-slicing once doing so

**Describe alternatives you've considered**

**Additional context**

**Comment by poodlewars** [comment]
Might as well tackle #699 with this.

@alexowens90 is also working on the defrag API - make sure to coordinate any changes with him in advance.

**Comment by alexowens90** [comment]
Superseded by https://github.com/man-group/ArcticDB/issues/719
