### ISSUE TITLE
In memory DB connection not working

### ISSUE THREAD

**Issue by rahulsk-cloudcraftz** [man-group/ArcticDB#936]
### Describe the bug

when i try to connect to in memory DB instance using 

`ac = Arctic('mem://')`

command I am getting invalid uri error. I wasn't able to find any solution online or any documentation which is referring to some other usage of this statement.

OS: ubuntu 22.04
Python: 3.10
Arctic version: 4.0.0

### Steps/Code to Reproduce

- Install ArcticDB
- Try to connect to in memory arcticDB connection using `ac = Arctic('mem://')`

### Expected Results

ValueError: Invalid URI specified. Please see URI format specification for available formats. uri=mem://

### OS, Python Version and ArcticDB Version

Python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
OS: Linux-6.2.0-34-generic-x86_64-with-glibc2.35
ArcticDB: 4.0.0

### Backend storage used

mem

**Comment by G-D-Petrov** [comment]
Hi @rahulsk-cloudcraftz, it seems that we have a bug in the documentation, sorry about that.
We don't support the in memory option for now, we expect to add it in the next release but that is tentative at the moment.
In the mean time, you are welcome to try to use lmdb as an alternative.

**Comment by rahulsk-cloudcraftz** [comment]
Thank you for clearing up this. I am closing this issue as the feature isn't released it.
