### ISSUE TITLE
Match Pandas default `NaN` handling in aggregations

### ISSUE THREAD

**Issue by alexowens90** [man-group/ArcticDB#958]
Min and max already (correctly) ignore NaNs when aggregating.
However, sum and mean will currently return NaN for any group that contains a NaN, which is less useful default behaviour than ignoring these values during the aggregation stage.

**Comment by DrNickClarke** [comment]
This is a duplicate of https://github.com/man-group/ArcticDB/issues/935
(which has testing code included)

**Comment by poodlewars** [comment]
Closing as dupe
