### ISSUE TITLE
Speed much slow down when using multi-columns filter for Query Builder

### ISSUE THREAD

**Issue by TianQingX** [man-group/ArcticDB#983]
**Is your feature request related to a problem? Please describe.**

def get_change_sample(q,prefix):
    sample = "state_change_category"
    search_sample = prefix + sample
    return (q[search_sample] != 0)

def get_change_sample(q,prefix):
    sample = "state_change_category"
    search_sample = get_target_columns(prefixes, sample)
    return (q[search_sample] != 0)

![image](https://github.com/man-group/ArcticDB/assets/40229906/e0d6c83b-c232-4b9c-8ee8-7fdae94b94d8)

![image](https://github.com/man-group/ArcticDB/assets/40229906/2fa01c5d-7de8-4f2f-840b-dbe72dbab854)

**Describe the solution you'd like**

speed is simply lower than 5 times, can we have a feature for speeding up this, such as intergrading the same condition query Builder from different symbols by arcticdb

**Describe alternatives you've considered**
I currently using numpy to concat the data, and the main efficient problem might be from Query Builder or numpy.

**Additional context**
It is currently running on filtering 21G data but it requires 250seconds for get all of it.

**Comment by poodlewars** [comment]
Hi @TianQingX sorry, I don't follow this report. Please can you describe your usecase and what exactly is slower than expected?
