### ISSUE TITLE
Empty column handling improvements

### ISSUE THREAD

**Issue by alexowens90** [man-group/ArcticDB#987]
Current behaviour (inferred, needs to be verified by looking at the code):

- Any columns with no values are stored as empty-type
- On read, empty-type columns are given dtype float64 for Pandas 1.X clients, and object for Pandas 2.X clients
- This leads to the inability to round-trip columns that have no values, but where the user explicitly specified a non-float64 numeric dtype

Desired behaviour:
- Columns of numeric (which includes datetimes) dtype != float64 with no values should always be stored with the provided dtype (never empty-type).
- Columns with no values of dtype float64 or object in Pandas 1.X should be stored with empty-type
- Columns with no values of dtype float64 in Pandas 2.X should be stored with with dtype float64
- Columns with no values of dtype object in Pandas 2.X should be stored with empty-type
- On read, empty-type columns should be converted to float64 for Pandas 1.X clients, and object for Pandas 2.X clients
- 
This means that the C++ layer will need to be aware of the Pandas version used to write the data.

Known limitations:

- Columns with no values of dtype object written with Pandas 1.X will be returned as type float64 (i.e. will not roundtrip correctly)
- Columns with no values and an explicitly specified dtype of float64 written with Pandas 1.X will be returned with dtype object when read with clients using Pandas 2.X
- Similarly, columns with no values and an explicitly specified dtype of objectwritten with Pandas 2.X will be returned with dtype float64 when read with clients using Pandas 1.X

```
| Reader / Writer | Pandas 1 Float | Pandas 1 Object | Pandas 2 Float | Pandas 2 Object |
| +++++++++++++++ | ++++++++++++++ | +++++++++++++++ | ++++++++++++++ | +++++++++++++++ |
| Pandas 1       || Float          | Float (!)       | Float          | Float (!)       |
| Pandas 2       || Object (OK)    | Object          | Float          | Object          |
```

**Comment by jjerphan** [comment]
> - On read, empty-type columns should be converted to float64 for Pandas 1.X clients, and object for Pandas 2.X clients

This is already done in the Python, here:
https://github.com/man-group/ArcticDB/blob/263e843015f010b4fcd30acb47b05a600b3d7448/python/arcticdb/version_store/_normalization.py#L581-L586
